package projectwork

import (
	"bytes"
	"fmt"
	"io/fs"
	"path"
	"sort"
	"strings"

	"github.com/Glacius-Labs/Markitect/src/internal/host/guardedwrite"
	"github.com/Glacius-Labs/Markitect/src/internal/host/projectcoverage"
	"github.com/Glacius-Labs/Markitect/src/internal/infrastructure/source"
	"github.com/Glacius-Labs/Markitect/src/internal/modules/projectmodel"
)

const ViewPath = ".markitect/views/project.md"
const DefaultDocumentPath = "docs/markitect/project.md"

// DocumentPath preserves the old hidden view for existing configurations.
// Newly initialized projects explicitly select the readable docs destination.
func DocumentPath(config Config) string {
	if config.DocumentPath != "" {
		return config.DocumentPath
	}
	return ViewPath
}

const generatedViewMarker = "<!-- Generated by Markitect projectwork; edit selected model sources instead. -->"

func IsGeneratedDocument(data []byte) bool {
	return bytes.HasPrefix(data, []byte(generatedViewMarker+"\n"))
}

// Document renders a readable view of the model: its Managers, Statements,
// Artifacts, checks and declared exclusions, the coverage verdict and only the
// paths and definitions that have a finding. It lists no repository inventory
// and no revision, so it changes only when the model or its findings change.
func Document(project *Project, write bool) (string, error) {
	if project == nil || project.Snapshot == nil {
		return "", fmt.Errorf("project snapshot is required")
	}
	content := documentText(project)
	if !write {
		return content, nil
	}
	if err := writeDocument(project, content); err != nil {
		return content, err
	}
	return content, nil
}

func writeDocument(project *Project, content string) error {
	viewPath := DocumentPath(project.Config)
	if !project.Provisional {
		return fmt.Errorf("writing a view requires a provisional current-working-tree Project")
	}
	current, err := Load(project.Root, "")
	if err != nil {
		return err
	}
	if current.Digest != project.Digest {
		return fmt.Errorf("project changed after the view was prepared")
	}
	paths := make([]string, 0, len(current.Snapshot.Files)+1)
	for file := range current.Snapshot.Files {
		paths = append(paths, file)
	}
	paths = append(paths, viewPath)
	paths = uniqueSorted(paths)
	capture, err := guardedwrite.CaptureFiles(project.Root, paths)
	if err != nil {
		return fmt.Errorf("capture generated project view: %w", err)
	}
	fileModeEnabled, err := source.GitFileModeEnabled(project.Root)
	if err != nil {
		return fmt.Errorf("inspect Git worktree mode policy: %w", err)
	}
	for file, data := range current.Snapshot.Files {
		actual, ok := capture.Files[file]
		if !ok || !actual.Exists || !bytes.Equal(actual.Bytes, data) || !sameSnapshotMode(actual.Mode, current.Snapshot.Modes[file], fileModeEnabled) {
			return fmt.Errorf("selected Project input changed before writing the view: %s", file)
		}
	}
	if existing, ok := capture.Files[viewPath]; ok && existing.Exists && !IsGeneratedDocument(existing.Bytes) {
		return fmt.Errorf("refusing to replace non-generated file at %s", viewPath)
	}
	validate := func() error {
		var current *Project
		var loadErr error
		if project.Provisional {
			current, loadErr = Load(project.Root, "")
		} else {
			current, loadErr = Load(project.Root, project.Revision)
		}
		if loadErr != nil {
			return loadErr
		}
		if current.Digest != project.Digest {
			return fmt.Errorf("selected project inputs changed before document write")
		}
		return nil
	}
	_, err = guardedwrite.ApplyChecked(capture.Root, capture, []guardedwrite.Change{{Path: viewPath, Bytes: []byte(content), Mode: fs.FileMode(0644)}}, validate)
	if err != nil {
		return fmt.Errorf("write generated view %s: %w", viewPath, err)
	}
	return nil
}

func documentText(project *Project) string {
	sourceLink := func(value string) string { return sourceLinkAt(DocumentPath(project.Config), value) }
	var out strings.Builder
	fmt.Fprintf(&out, "%s\n\n# %s\n\n", generatedViewMarker, heading(project.Config.Name))
	// The revision and the project binding change with every commit, so the
	// header names only the semantic model digest and the report status.
	fmt.Fprintf(&out, "Model digest: %s\n\nReport status: %s\n\n", project.Model.Digest, project.Report.Status)
	out.WriteString("The structural model compiled from the explicitly selected Definition files. This view does not establish that repository code, tests, or prose conform to the model. Declared checks are not evidence that they ran.\n\n")

	out.WriteString("## Responsibilities\n\n")
	managers := append([]projectmodel.Manager(nil), project.Report.Managers...)
	sort.Slice(managers, func(i, j int) bool { return managers[i].ID < managers[j].ID })
	if len(managers) == 0 {
		out.WriteString("No Manager definitions are selected.\n\n")
	} else {
		for _, manager := range managers {
			fmt.Fprintf(&out, "### %s\n\n- Identity: %s\n- Namespace: %s\n", heading(manager.Name), manager.ID, manager.Namespace)
			if manager.Purpose != "" {
				fmt.Fprintf(&out, "- Purpose: %s\n", inline(manager.Purpose))
			}
			if manager.Parent != "" {
				fmt.Fprintf(&out, "- Parent Manager: %s\n", manager.Parent)
			}
			if len(manager.Owns) > 0 {
				fmt.Fprintf(&out, "- Delegated paths: %s\n", list(manager.Owns))
			}
			if manager.Instructions != "" {
				fmt.Fprintf(&out, "- Instructions: %s\n", inline(manager.Instructions))
			}
			out.WriteString("\n")
		}
	}

	out.WriteString("## Statements\n\n")
	statements := append([]projectmodel.Statement(nil), project.Report.Statements...)
	sort.Slice(statements, func(i, j int) bool { return statements[i].ID < statements[j].ID })
	if len(statements) == 0 {
		out.WriteString("No Statements are selected.\n\n")
	} else {
		for _, statement := range statements {
			fmt.Fprintf(&out, "### %s\n\n- Identity: %s\n- Category: %s\n- Responsible Manager: %s\n- Source: %s\n\n%s\n\n",
				heading(statement.Name), statement.ID, inline(statement.Category), statement.Owner, sourceLink(statement.Source), inline(statement.Description))
			if len(statement.Requires) > 0 {
				fmt.Fprintf(&out, "Requires: %s\n\n", list(statement.Requires))
			}
			if len(statement.Uses) > 0 {
				fmt.Fprintf(&out, "Uses: %s\n\n", list(statement.Uses))
			}
		}
	}

	out.WriteString("## Expected artifacts\n\n")
	artifacts := append([]projectmodel.Artifact(nil), project.Report.Artifacts...)
	sort.Slice(artifacts, func(i, j int) bool { return artifacts[i].ID < artifacts[j].ID })
	if len(artifacts) == 0 {
		out.WriteString("No Artifact expectations are selected.\n\n")
	} else {
		for _, artifact := range artifacts {
			requirement := "optional"
			if artifact.Required {
				requirement = "required"
			}
			fmt.Fprintf(&out, "### %s\n\n- Identity: %s\n- Requirement: %s\n- Role: %s\n- Responsible Manager: %s\n",
				heading(artifact.Name), artifact.ID, requirement, inline(artifact.Role), artifact.Owner)
			if len(artifact.Realizes) > 0 {
				fmt.Fprintf(&out, "- Realizes: %s\n", list(artifact.Realizes))
			}
			if len(artifact.Paths) > 0 {
				fmt.Fprintf(&out, "- Expected paths: %s\n", pathList(artifact.Paths, sourceLink))
			} else {
				out.WriteString("- Expected paths: not assigned\n")
			}
			if len(artifact.Checks) > 0 {
				fmt.Fprintf(&out, "- Related checks: %s (declared; execution not observed)\n", list(artifact.Checks))
			} else {
				out.WriteString("- Related checks: none declared\n")
			}
			if artifact.Reason != "" {
				fmt.Fprintf(&out, "- Applicability: %s\n", inline(artifact.Reason))
			}
			out.WriteString("\n")
		}
	}

	out.WriteString("## Declared checks\n\n")
	checks := append([]projectmodel.Check(nil), project.Report.Checks...)
	sort.Slice(checks, func(i, j int) bool { return checks[i].ID < checks[j].ID })
	if len(checks) == 0 {
		out.WriteString("No checks are declared.\n\n")
	} else {
		for _, check := range checks {
			fmt.Fprintf(&out, "- %s (%s), owned by %s: %s — declared only; no run result is bound to this report.\n",
				inline(check.Name), check.ID, inline(check.Owner), shellDisplay(check.Command))
			if check.Limitation != "" {
				fmt.Fprintf(&out, "  - Limit: %s\n", inline(check.Limitation))
			}
		}
		out.WriteString("\n")
	}

	writeDeclaredExclusions(&out, project)
	writeCoverageAndFindings(&out, project)
	return trimLineEnds(out.String())
}

// writeDeclaredExclusions lists the paths the project declares outside its
// modelled realization, each with its declared reason.
func writeDeclaredExclusions(out *strings.Builder, project *Project) {
	out.WriteString("## Declared exclusions\n\n")
	var lines []string
	add := func(label string, entries []Exclusion) {
		sorted := append([]Exclusion(nil), entries...)
		sort.Slice(sorted, func(i, j int) bool { return sorted[i].Path < sorted[j].Path })
		for _, entry := range sorted {
			lines = append(lines, fmt.Sprintf("- %s: %s — %s\n", label, inline(entry.Path), inline(entry.Reason)))
		}
	}
	if project.Config.CoverageMode == "full" {
		ignored, err := declaredIgnores(project)
		if err != nil {
			lines = append(lines, fmt.Sprintf("- Ignored: %s cannot be read: %s\n", projectcoverage.IgnorePath, inline(err.Error())))
		}
		add("Ignored", ignored)
		add("Transitional", project.Config.TransitionalExclusions)
		add("Legacy exclusion (no effect on full coverage)", project.Config.Exclusions)
	} else {
		add("Excluded from the selected inventory", project.Config.Exclusions)
		add("Transitional", project.Config.TransitionalExclusions)
	}
	if len(lines) == 0 {
		out.WriteString("No exclusions are declared.\n\n")
		return
	}
	for _, line := range lines {
		out.WriteString(line)
	}
	out.WriteString("\n")
}

// declaredIgnores reads the entries of the repository ignore file that the
// project snapshot binds; a project without one ignores nothing.
func declaredIgnores(project *Project) ([]Exclusion, error) {
	if project.Snapshot == nil {
		return nil, nil
	}
	data, ok := project.Snapshot.Files[projectcoverage.IgnorePath]
	if !ok {
		return nil, nil
	}
	ignore, err := projectcoverage.DecodeIgnore(data)
	if err != nil {
		return nil, err
	}
	entries := make([]Exclusion, 0, len(ignore.Entries))
	for _, entry := range ignore.Entries {
		entries = append(entries, Exclusion{Path: entry.Path, Reason: entry.Reason})
	}
	return entries, nil
}

// writeCoverageAndFindings states the coverage verdict and lists only the
// paths and definitions that have a finding. Paths without one stay out of the
// view, so adding or removing a conforming file leaves it unchanged.
func writeCoverageAndFindings(out *strings.Builder, project *Project) {
	out.WriteString("## Coverage and findings\n\n")
	full := project.Config.CoverageMode == "full"
	switch {
	case full && project.Coverage != nil:
		fmt.Fprintf(out, "- Coverage mode: full (the whole repository)\n- Accounted: %s\n- Conforming: %s\n\n",
			yesNo(project.Coverage.Accounted), yesNo(project.Coverage.Conforming))
	case full:
		out.WriteString("- Coverage mode: full (the whole repository)\n- Accounted: not classified for this view\n- Conforming: not classified for this view\n\n")
	case len(project.Config.InventoryRoots) == 0:
		out.WriteString("- Coverage mode: selected (no inventory roots are selected; repository paths are not classified)\n\n")
	default:
		fmt.Fprintf(out, "- Coverage mode: selected (only the inventory roots %s are observed; other paths are not classified)\n\n", list(project.Config.InventoryRoots))
	}
	findings := map[string][]string{}
	add := func(subject, text string) { findings[subject] = append(findings[subject], text) }
	for _, unknown := range project.Report.Unknown {
		add(unknown, "unowned: no Manager owns this path")
	}
	if !full {
		// Full coverage reports a file without an Artifact as unclassified.
		for _, file := range project.Report.Files {
			if file.Exists && len(file.Artifacts) == 0 {
				add(file.Path, "unmodeled: no Artifact path declared")
			}
		}
	}
	for _, finding := range project.Report.Findings {
		add(finding.Subject, fmt.Sprintf("%s (%s): %s", inline(finding.Severity), inline(finding.Code), inline(finding.Message)))
	}
	if full && project.Coverage != nil {
		for _, finding := range project.Coverage.Findings {
			add(finding.Path, fmt.Sprintf("%s (%s): %s", inline(finding.Severity), inline(finding.Code), inline(finding.Message)))
		}
		// A present file under a transitional exclusion blocks conformance
		// without a coverage finding; list it so the verdict has a reason.
		for _, entry := range project.Coverage.Entries {
			present := entry.Head.Present
			if project.Provisional {
				present = entry.Worktree.Present
			}
			if entry.Class == projectcoverage.ClassTransitional && present {
				add(entry.Path, fmt.Sprintf("transitional: blocks conformance until the path is classified (%s)", inline(entry.Reason)))
			}
		}
	}
	if len(findings) == 0 {
		out.WriteString("No path or definition has a finding.\n")
		return
	}
	out.WriteString("Only the paths and definitions with a finding are listed.\n\n")
	subjects := make([]string, 0, len(findings))
	for subject := range findings {
		subjects = append(subjects, subject)
	}
	sort.Strings(subjects)
	for _, subject := range subjects {
		name := inline(subject)
		if strings.TrimSpace(subject) == "" {
			name = "(project)"
		}
		fmt.Fprintf(out, "- %s\n", name)
		for _, text := range uniqueSorted(findings[subject]) {
			fmt.Fprintf(out, "  - %s\n", text)
		}
	}
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

// trimLineEnds drops the spaces and tabs that empty or newline-terminated model
// values leave at the end of a line, such as a root Manager's empty Namespace.
func trimLineEnds(text string) string {
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		lines[i] = strings.TrimRight(line, " \t")
	}
	return strings.Join(lines, "\n")
}

func heading(value string) string { return strings.TrimSpace(strings.ReplaceAll(value, "\n", " ")) }
func inline(value string) string {
	return strings.NewReplacer("\r", " ", "\n", " ", "|", "\\|").Replace(value)
}

func list(values []string) string {
	copyValues := append([]string(nil), values...)
	sort.Strings(copyValues)
	for i, value := range copyValues {
		copyValues[i] = inline(value)
	}
	return strings.Join(copyValues, ", ")
}

func pathList(values []string, link func(string) string) string {
	copyValues := append([]string(nil), values...)
	sort.Strings(copyValues)
	for i, value := range copyValues {
		copyValues[i] = link(value)
	}
	return strings.Join(copyValues, ", ")
}

func sourceLinkAt(destination, value string) string {
	clean := path.Clean(strings.TrimPrefix(value, "/"))
	if clean == "." || strings.HasPrefix(clean, "../") || strings.Contains(clean, "\\") {
		return inline(value)
	}
	relative, ok := relativeSlashPath(path.Dir(destination), clean)
	if !ok {
		return inline(value)
	}
	return "[" + inline(value) + "](" + strings.ReplaceAll(relative, " ", "%20") + ")"
}

// relativeSlashPath works like filepath.Rel on clean repository slash paths but
// compares names case-sensitively, so links are the same bytes on every OS.
func relativeSlashPath(base, target string) (string, bool) {
	for _, value := range []string{base, target} {
		if strings.HasPrefix(value, "/") || value == ".." || strings.HasPrefix(value, "../") {
			return "", false
		}
	}
	if base == "." {
		return target, true
	}
	from, to := strings.Split(base, "/"), strings.Split(target, "/")
	common := 0
	for common < len(from) && common < len(to) && from[common] == to[common] {
		common++
	}
	parts := make([]string, 0, len(from)-common+len(to)-common)
	for range from[common:] {
		parts = append(parts, "..")
	}
	parts = append(parts, to[common:]...)
	if len(parts) == 0 {
		return ".", true
	}
	return strings.Join(parts, "/"), true
}

func shellDisplay(command []string) string {
	if len(command) == 0 {
		return "(empty command)"
	}
	return strings.Join(command, " ")
}
