// Package publish prepares and, when explicitly requested, publishes an
// immutable GitHub release for the fixed Markitect repository.
package publish

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/Glacius-Labs/Markitect/internal/release"
	"go.yaml.in/yaml/v3"
)

const repository = "Glacius-Labs/Markitect"
const workflowPath = ".github/workflows/release.yaml"

var semverTag = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$`)
var digestPattern = regexp.MustCompile(`^[0-9a-f]{64}$`)
var commitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)

var errDraftStillPending = errors.New("GitHub confirms the release is still a draft")

// Runner executes gh without taking or copying a credential. Production callers
// should inherit the authenticated environment established by gh auth login.
type Runner interface {
	Run(context.Context, string, ...string) ([]byte, error)
}

type Options struct {
	Tag       string
	RunID     string
	AssetsDir string
	Publish   bool
}

type Asset struct {
	Name   string `yaml:"name" json:"name"`
	SHA256 string `yaml:"sha256" json:"sha256"`
}

// Provenance is the strict metadata generated by the release workflow.
type Provenance struct {
	SchemaVersion      string  `yaml:"schemaVersion"`
	Tag                string  `yaml:"tag"`
	SourceCommit       string  `yaml:"sourceCommit"`
	WorkflowRunID      string  `yaml:"workflowRunId"`
	WorkflowRunAttempt string  `yaml:"workflowRunAttempt"`
	WorkflowRun        string  `yaml:"workflowRun"`
	Toolchain          string  `yaml:"toolchain"`
	Assets             []Asset `yaml:"assets"`
}

type Result struct {
	Status          string   `yaml:"status" json:"status"`
	Repository      string   `yaml:"repository" json:"repository"`
	Tag             string   `yaml:"tag" json:"tag"`
	SourceCommit    string   `yaml:"sourceCommit" json:"sourceCommit"`
	WorkflowRunID   string   `yaml:"workflowRunId" json:"workflowRunId"`
	WorkflowAttempt int      `yaml:"workflowRunAttempt" json:"workflowRunAttempt"`
	Version         string   `yaml:"version" json:"version"`
	Assets          []Asset  `yaml:"assets" json:"assets"`
	ReleaseID       int64    `yaml:"releaseId,omitempty" json:"releaseId,omitempty"`
	Immutable       bool     `yaml:"immutable,omitempty" json:"immutable,omitempty"`
	Steps           []string `yaml:"steps" json:"steps"`
}

type runInfo struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	Event      string `json:"event"`
	Status     string `json:"status"`
	Conclusion string `json:"conclusion"`
	HeadBranch string `json:"head_branch"`
	HeadSHA    string `json:"head_sha"`
	RunAttempt int    `json:"run_attempt"`
}

type artifactList struct {
	Artifacts []struct {
		Name        string `json:"name"`
		Expired     bool   `json:"expired"`
		WorkflowRun struct {
			ID int64 `json:"id"`
		} `json:"workflow_run"`
	} `json:"artifacts"`
}

type repoInfo struct {
	FullName    string `json:"full_name"`
	Permissions struct {
		Admin bool `json:"admin"`
	} `json:"permissions"`
}

type refInfo struct {
	Object struct {
		Type string `json:"type"`
		SHA  string `json:"sha"`
	} `json:"object"`
}
type tagInfo struct {
	Object struct {
		Type string `json:"type"`
		SHA  string `json:"sha"`
	} `json:"object"`
}
type releaseInfo struct {
	ID        int64         `json:"id"`
	TagName   string        `json:"tag_name"`
	Draft     bool          `json:"draft"`
	Immutable bool          `json:"immutable"`
	Assets    []remoteAsset `json:"assets"`
}
type remoteAsset struct {
	Name   string `json:"name"`
	Digest string `json:"digest"`
}

// Execute performs a complete read-only publication preflight by default.
// With Publish it repeats mutable remote checks before each state transition.
func Execute(ctx context.Context, runner Runner, options Options) (*Result, error) {
	if runner == nil {
		return nil, errors.New("GitHub command runner is required")
	}
	if !semverTag.MatchString(options.Tag) {
		return nil, fmt.Errorf("tag %q is not a supported vSemVer", options.Tag)
	}
	if options.RunID == "" {
		return nil, errors.New("workflow run ID is required")
	}
	if options.AssetsDir == "" {
		return nil, errors.New("local asset directory is required")
	}
	if _, err := strconv.ParseInt(options.RunID, 10, 64); err != nil {
		return nil, errors.New("workflow run ID must be numeric")
	}

	assets, err := readAssets(options.AssetsDir, options.Tag)
	if err != nil {
		return nil, err
	}
	result := &Result{Status: "preflight-passed", Repository: repository, Tag: options.Tag, Assets: assetRows(assets)}
	result.Steps = append(result.Steps, "publish operations are sequential, not transactional; any failure after draft creation leaves it for manual review")
	if err := call(runner, ctx, "", "auth", "status", "--hostname", "github.com"); err != nil {
		return nil, fmt.Errorf("gh auth status failed: %w", err)
	}
	result.Steps = append(result.Steps, "gh owner-authenticated session available")

	var repo repoInfo
	if err := apiJSON(runner, ctx, "repos/"+repository, &repo); err != nil {
		return nil, fmt.Errorf("read repository permissions: %w", err)
	}
	if repo.FullName != repository || !repo.Permissions.Admin {
		return nil, errors.New("authenticated gh user is not an administrator of the fixed repository")
	}
	var imm struct {
		Enabled bool `json:"enabled"`
	}
	if err := apiJSON(runner, ctx, "repos/"+repository+"/immutable-releases", &imm); err != nil {
		return nil, fmt.Errorf("read immutable-release setting: %w", err)
	}
	if !imm.Enabled {
		return nil, errors.New("GitHub immutable releases are not enabled")
	}
	result.Steps = append(result.Steps, "owner permission and immutable-release setting confirmed")

	runID, _ := strconv.ParseInt(options.RunID, 10, 64)
	var run runInfo
	if err := apiJSON(runner, ctx, fmt.Sprintf("repos/%s/actions/runs/%d", repository, runID), &run); err != nil {
		return nil, fmt.Errorf("read selected workflow run: %w", err)
	}
	path := strings.SplitN(run.Path, "@", 2)[0]
	if run.ID != runID || run.Status != "completed" || run.Conclusion != "success" || run.Event != "push" || path != workflowPath || run.HeadBranch != options.Tag || !commitPattern.MatchString(run.HeadSHA) || run.RunAttempt < 1 {
		return nil, errors.New("selected run is not a successful completed push of the fixed release workflow for this tag")
	}
	if err := validateTagTarget(runner, ctx, options.Tag, run.HeadSHA); err != nil {
		return nil, err
	}
	var artifacts artifactList
	if err := apiJSON(runner, ctx, fmt.Sprintf("repos/%s/actions/runs/%d/artifacts", repository, runID), &artifacts); err != nil {
		return nil, fmt.Errorf("read workflow artifacts: %w", err)
	}
	artifactName := "markitect-release-" + run.HeadSHA
	found := false
	for _, artifact := range artifacts.Artifacts {
		if artifact.Name == artifactName && !artifact.Expired && artifact.WorkflowRun.ID == runID {
			if found {
				return nil, errors.New("workflow run has duplicate release transport artifacts")
			}
			found = true
		}
	}
	if !found {
		return nil, fmt.Errorf("selected workflow run has no unexpired artifact %q", artifactName)
	}

	remoteAssets, err := downloadAndValidateArtifact(ctx, runner, options.RunID, artifactName, options.Tag, run)
	if err != nil {
		return nil, err
	}
	if !sameAssetBytes(assets, remoteAssets) {
		return nil, errors.New("local assets differ byte-for-byte from the selected successful workflow artifact")
	}
	result.SourceCommit = run.HeadSHA
	result.WorkflowRunID = options.RunID
	result.WorkflowAttempt = run.RunAttempt
	result.Version = strings.TrimPrefix(options.Tag, "v")
	result.Steps = append(result.Steps, "exact run-scoped artifact and all four local payload bytes verified")

	bundle := assets["markitect-"+options.Tag+"-bundle.zip"]
	parsedBundle, err := release.ParseBundle(bundle, digest(bundle))
	if err != nil {
		return nil, fmt.Errorf("release bundle validation failed: %w", err)
	}
	if parsedBundle.Manifest.Version != strings.TrimPrefix(options.Tag, "v") || parsedBundle.Manifest.SourceCommit != run.HeadSHA || parsedBundle.Manifest.SourceRepository != "github.com/Glacius-Labs/Markitect" {
		return nil, errors.New("bundle manifest version, source commit, or source repository does not match the selected release run")
	}
	result.Steps = append(result.Steps, "bundle manifest and four pinned files validate for the tagged version")
	if _, err := getRelease(runner, ctx, options.Tag); err == nil {
		return nil, fmt.Errorf("a GitHub release already exists for %s; existing drafts and releases are never replaced or resumed", options.Tag)
	} else if !isNotFound(err) {
		return nil, fmt.Errorf("could not safely check for an existing release: %w", err)
	}
	result.Steps = append(result.Steps, "no existing release or draft for tag")
	if !options.Publish {
		return result, nil
	}
	uploadDir, err := stageVerifiedAssets(assets, options.Tag)
	if err != nil {
		return nil, fmt.Errorf("stage verified release assets: %w", err)
	}
	defer os.RemoveAll(uploadDir)

	if err := validateTagTarget(runner, ctx, options.Tag, run.HeadSHA); err != nil {
		return nil, err
	}
	if err := checkImmutable(runner, ctx); err != nil {
		return nil, err
	}
	if _, err := getRelease(runner, ctx, options.Tag); err == nil {
		return nil, errors.New("release appeared after preflight; refusing to publish")
	} else if !isNotFound(err) {
		return nil, fmt.Errorf("recheck release name: %w", err)
	}
	draft, err := createDraft(runner, ctx, options.Tag, run.HeadSHA)
	if err != nil {
		return nil, fmt.Errorf("create empty draft failed (if the request reached GitHub, inspect the tag draft before retrying): %w", err)
	}
	result.ReleaseID = draft.ID
	result.Status = "draft-created"
	// Once a draft exists, failures intentionally leave it for manual review.
	// Re-running is rejected rather than attempting ambiguous resume semantics.
	assetPaths := make([]string, 0, len(assetNames(options.Tag)))
	for _, name := range assetNames(options.Tag) {
		assetPaths = append(assetPaths, filepath.Join(uploadDir, name))
	}
	args := []string{"release", "upload", options.Tag}
	args = append(args, assetPaths...)
	args = append(args, "--repo", "github.com/"+repository)
	if err := call(runner, ctx, "", args...); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; asset upload failed: %w", draft.ID, err)
	}
	if err := verifyDraftAssets(runner, ctx, draft.ID, assets); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; uploaded asset verification failed: %w", draft.ID, err)
	}
	if err := validateTagTarget(runner, ctx, options.Tag, run.HeadSHA); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; tag changed before publication: %w", draft.ID, err)
	}
	if err := checkImmutable(runner, ctx); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; immutable setting changed: %w", draft.ID, err)
	}
	if err := patchDraft(runner, ctx, draft.ID, options.Tag); err != nil {
		if errors.Is(err, errDraftStillPending) {
			result.Status = "draft-created"
			return result, fmt.Errorf("draft %d remains for manual review; GitHub confirmed it is still a draft: %w", draft.ID, err)
		}
		result.Status = "publication-unknown"
		return result, fmt.Errorf("publication outcome for release %d is unknown; inspect the tag and release state manually before retrying: %w", draft.ID, err)
	}
	result.Status = "published-verified"
	if err := verifyPublished(runner, ctx, options.Tag, run.HeadSHA, draft.ID, assets, uploadDir); err != nil {
		result.Status = "published-unverified"
		return result, fmt.Errorf("release %d may be published but verification failed: %w", draft.ID, err)
	}
	result.Immutable = true
	result.Steps = append(result.Steps, "draft assets verified; release published immutable; release and each asset attestation verified; tag target rechecked")
	return result, nil
}

type namedBytes map[string][]byte

func assetNames(tag string) []string {
	return []string{"markitect-" + tag + "-bundle.zip", "markitect-" + tag + "-linux-amd64", "markitect-" + tag + "-windows-amd64.exe", "markitect-" + tag + "-provenance.yaml"}
}

func readAssets(dir, tag string) (namedBytes, error) {
	dirInfo, err := os.Lstat(dir)
	if err != nil {
		return nil, fmt.Errorf("inspect asset directory: %w", err)
	}
	if !dirInfo.IsDir() || dirInfo.Mode()&os.ModeSymlink != 0 {
		return nil, errors.New("asset directory must be a real directory, not a symlink")
	}
	names := assetNames(tag)
	expected := make(map[string]bool, len(names))
	for _, n := range names {
		expected[n] = true
	}
	dirEntries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	entries := make([]string, 0, len(dirEntries))
	for _, entry := range dirEntries {
		entries = append(entries, filepath.Join(dir, entry.Name()))
	}
	if len(entries) != len(names) {
		return nil, fmt.Errorf("asset directory must contain exactly four regular files named %s", strings.Join(names, ", "))
	}
	out := make(namedBytes, len(names))
	for _, path := range entries {
		fileInfo, err := os.Lstat(path)
		if err != nil {
			return nil, err
		}
		if !fileInfo.Mode().IsRegular() {
			return nil, fmt.Errorf("asset %s is not a regular file", filepath.Base(path))
		}
		name := filepath.Base(path)
		if !expected[name] {
			return nil, fmt.Errorf("unexpected release asset %q", name)
		}
		limit := int64(256 << 20)
		if name == names[0] {
			limit = 64 << 20
		} else if name == names[3] {
			limit = 64 << 10
		}
		data, err := readLimited(path, limit)
		if err != nil {
			return nil, err
		}
		out[name] = data
	}
	for _, name := range names {
		if _, ok := out[name]; !ok {
			return nil, fmt.Errorf("release asset %q is missing", name)
		}
	}
	prov, err := parseProvenance(out[names[3]])
	if err != nil {
		return nil, err
	}
	if prov.Tag != tag || prov.SchemaVersion != "1" || strings.TrimSpace(prov.Toolchain) == "" {
		return nil, errors.New("provenance schema, tag, or toolchain is invalid")
	}
	if len(prov.Assets) != 3 {
		return nil, errors.New("provenance must bind exactly the three payload assets")
	}
	for i, name := range names[:3] {
		if prov.Assets[i].Name != name || !digestPattern.MatchString(prov.Assets[i].SHA256) || prov.Assets[i].SHA256 != digest(out[name]) {
			return nil, fmt.Errorf("provenance digest for %s is invalid", name)
		}
	}
	return out, nil
}

// Parsing checks duplicate YAML keys as well as unknown fields. The provenance
// is a claim until its selected run artifact has been independently fetched.
func parseProvenance(data []byte) (Provenance, error) {
	var node yaml.Node
	dec := yaml.NewDecoder(bytes.NewReader(data))
	if err := dec.Decode(&node); err != nil {
		return Provenance{}, fmt.Errorf("decode provenance: %w", err)
	}
	if err := rejectDuplicateYAML(&node); err != nil {
		return Provenance{}, err
	}
	var extra yaml.Node
	if err := dec.Decode(&extra); err != io.EOF {
		return Provenance{}, errors.New("provenance must contain one YAML document")
	}
	dec = yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(true)
	var p Provenance
	if err := dec.Decode(&p); err != nil {
		return p, fmt.Errorf("decode provenance fields: %w", err)
	}
	if p.SchemaVersion != "1" || p.Tag == "" || !commitPattern.MatchString(p.SourceCommit) || p.WorkflowRunID == "" || p.WorkflowRunAttempt == "" || p.WorkflowRun == "" || p.Toolchain == "" {
		return p, errors.New("provenance is missing required schema or source/run fields")
	}
	return p, nil
}

func rejectDuplicateYAML(n *yaml.Node) error {
	if n.Anchor != "" || n.Kind == yaml.AliasNode {
		return errors.New("provenance YAML anchors and aliases are not allowed")
	}
	if n.Tag != "" && n.Tag != "!!map" && n.Tag != "!!seq" && n.Tag != "!!str" {
		return fmt.Errorf("provenance contains unsupported YAML tag %s", n.Tag)
	}
	if n.Kind == yaml.MappingNode {
		seen := map[string]bool{}
		for i := 0; i < len(n.Content); i += 2 {
			k := n.Content[i]
			if k.Kind != yaml.ScalarNode || k.Tag != "!!str" {
				return errors.New("provenance mapping keys must be strings")
			}
			if seen[k.Value] {
				return fmt.Errorf("provenance contains duplicate field %q", k.Value)
			}
			seen[k.Value] = true
		}
	}
	for _, child := range n.Content {
		if err := rejectDuplicateYAML(child); err != nil {
			return err
		}
	}
	return nil
}

func downloadAndValidateArtifact(ctx context.Context, r Runner, runID, name, tag string, run runInfo) (namedBytes, error) {
	dir, err := os.MkdirTemp("", "markitect-release-artifact-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(dir)
	if err := call(r, ctx, "", "run", "download", runID, "--repo", "github.com/"+repository, "--name", name, "--dir", dir); err != nil {
		return nil, fmt.Errorf("download selected run artifact: %w", err)
	}
	assets, err := readAssets(dir, tag)
	if err != nil {
		return nil, fmt.Errorf("downloaded artifact is invalid: %w", err)
	}
	prov, err := parseProvenance(assets[assetNames(tag)[3]])
	if err != nil {
		return nil, err
	}
	wantURL := fmt.Sprintf("https://github.com/%s/actions/runs/%d/attempts/%d", repository, run.ID, run.RunAttempt)
	if prov.SourceCommit != run.HeadSHA || prov.WorkflowRunID != strconv.FormatInt(run.ID, 10) || prov.WorkflowRunAttempt != strconv.Itoa(run.RunAttempt) || prov.WorkflowRun != wantURL {
		return nil, errors.New("artifact provenance does not match selected workflow run, attempt, source commit, and repository URL")
	}
	return assets, nil
}

func validateTagTarget(r Runner, ctx context.Context, tag, commit string) error {
	var ref refInfo
	if err := apiJSON(r, ctx, "repos/"+repository+"/git/ref/tags/"+url.PathEscape(tag), &ref); err != nil {
		return fmt.Errorf("read remote tag: %w", err)
	}
	kind, sha := ref.Object.Type, ref.Object.SHA
	for depth := 0; kind == "tag"; depth++ {
		if depth >= 8 {
			return errors.New("annotated tag chain exceeds eight objects")
		}
		var annotated tagInfo
		if err := apiJSON(r, ctx, "repos/"+repository+"/git/tags/"+sha, &annotated); err != nil {
			return fmt.Errorf("read annotated tag: %w", err)
		}
		kind, sha = annotated.Object.Type, annotated.Object.SHA
	}
	if kind != "commit" || sha != commit || !commitPattern.MatchString(sha) {
		return errors.New("current remote tag does not resolve to the selected workflow source commit")
	}
	return nil
}

func getRelease(r Runner, ctx context.Context, tag string) (releaseInfo, error) {
	var x releaseInfo
	err := apiJSON(r, ctx, "repos/"+repository+"/releases/tags/"+url.PathEscape(tag), &x)
	return x, err
}
func checkImmutable(r Runner, ctx context.Context) error {
	var x struct {
		Enabled bool `json:"enabled"`
	}
	if err := apiJSON(r, ctx, "repos/"+repository+"/immutable-releases", &x); err != nil {
		return err
	}
	if !x.Enabled {
		return errors.New("immutable releases are not enabled")
	}
	return nil
}

func createDraft(r Runner, ctx context.Context, tag, commit string) (releaseInfo, error) {
	body := "Private Markitect release for source commit " + commit + ". See the provenance YAML asset for the source, run, toolchain, and release asset digests."
	// Structured gh fields preserve each value as one process argument without
	// shell interpolation or temporary note files.
	prerelease := isPrereleaseTag(tag)
	args := []string{"api", "--hostname", "github.com", "repos/" + repository + "/releases", "-X", "POST", "-f", "tag_name=" + tag, "-f", "target_commitish=" + commit, "-f", "name=Markitect " + tag, "-f", "body=" + body, "-F", "draft=true", "-F", "prerelease=" + strconv.FormatBool(prerelease)}
	out, err := r.Run(ctx, "", args...)
	if err != nil {
		return releaseInfo{}, err
	}
	var x releaseInfo
	if err := json.Unmarshal(out, &x); err != nil {
		return x, fmt.Errorf("decode created draft response: %w", err)
	}
	if x.ID == 0 || x.TagName != tag || !x.Draft || len(x.Assets) != 0 {
		return x, errors.New("GitHub did not create the expected empty draft")
	}
	return x, nil
}

func verifyDraftAssets(r Runner, ctx context.Context, id int64, files namedBytes) error {
	var x []remoteAsset
	if err := apiJSON(r, ctx, fmt.Sprintf("repos/%s/releases/%d/assets", repository, id), &x); err != nil {
		return err
	}
	return compareRemoteAssets(x, files)
}
func compareRemoteAssets(remote []remoteAsset, files namedBytes) error {
	if len(remote) != 4 || len(files) != 4 {
		return errors.New("release must contain exactly four assets")
	}
	got := map[string]string{}
	for _, a := range remote {
		if _, dup := got[a.Name]; dup {
			return fmt.Errorf("duplicate uploaded asset %q", a.Name)
		}
		got[a.Name] = a.Digest
	}
	for name, data := range files {
		want := "sha256:" + digest(data)
		if got[name] != want {
			return fmt.Errorf("uploaded asset %s digest mismatch", name)
		}
	}
	return nil
}
func patchDraft(r Runner, ctx context.Context, id int64, tag string) error {
	out, err := r.Run(ctx, "", "api", "--hostname", "github.com", fmt.Sprintf("repos/%s/releases/%d", repository, id), "-X", "PATCH", "-F", "draft=false")
	if err != nil {
		return err
	}
	var x releaseInfo
	if err := json.Unmarshal(out, &x); err != nil {
		return err
	}
	if x.ID != id || x.TagName != tag {
		return fmt.Errorf("GitHub returned an unexpected release ID %d during publication", x.ID)
	}
	if x.Draft {
		return errDraftStillPending
	}
	return nil
}

func isPrereleaseTag(tag string) bool {
	version := strings.TrimPrefix(tag, "v")
	version = strings.SplitN(version, "+", 2)[0]
	return strings.Contains(version, "-")
}
func verifyPublished(r Runner, ctx context.Context, tag, commit string, id int64, files namedBytes, assetDir string) error {
	var x releaseInfo
	if err := apiJSON(r, ctx, fmt.Sprintf("repos/%s/releases/%d", repository, id), &x); err != nil {
		return err
	}
	if x.ID != id || x.TagName != tag || x.Draft || !x.Immutable {
		return errors.New("published release is not the expected immutable release")
	}
	if err := compareRemoteAssets(x.Assets, files); err != nil {
		return err
	}
	if err := call(r, ctx, "", "release", "verify", tag, "--repo", "github.com/"+repository); err != nil {
		return fmt.Errorf("release attestation verification failed: %w", err)
	}
	for _, name := range assetNames(tag) {
		if err := call(r, ctx, "", "release", "verify-asset", tag, filepath.Join(assetDir, name), "--repo", "github.com/"+repository); err != nil {
			return fmt.Errorf("asset attestation verification failed for %s: %w", name, err)
		}
	}
	if err := checkImmutable(r, ctx); err != nil {
		return fmt.Errorf("immutable-release setting changed after publication: %w", err)
	}
	return validateTagTarget(r, ctx, tag, commit)
}

type APIError struct {
	Status  int
	Message string
}

func (e *APIError) Error() string { return fmt.Sprintf("GitHub API HTTP %d: %s", e.Status, e.Message) }
func apiJSON(r Runner, ctx context.Context, endpoint string, target any) error {
	out, err := r.Run(ctx, "", "api", "--hostname", "github.com", "--include", "-H", "X-GitHub-Api-Version: 2026-03-10", endpoint)
	body, status, parseErr := splitHTTPResponse(out)
	if parseErr != nil {
		if err != nil {
			return err
		}
		return parseErr
	}
	if status < 200 || status >= 300 {
		message := strings.TrimSpace(string(body))
		if len(message) > 512 {
			message = message[:512]
		}
		return &APIError{Status: status, Message: message}
	}
	if err != nil {
		return err
	}
	if err := json.Unmarshal(body, target); err != nil {
		return fmt.Errorf("decode GitHub API response for %s: %w", endpoint, err)
	}
	return nil
}
func call(r Runner, ctx context.Context, dir string, args ...string) error {
	_, err := r.Run(ctx, dir, args...)
	return err
}
func isNotFound(err error) bool {
	var apiErr *APIError
	return errors.As(err, &apiErr) && apiErr.Status == 404
}
func digest(data []byte) string { sum := sha256.Sum256(data); return hex.EncodeToString(sum[:]) }
func assetRows(files namedBytes) []Asset {
	rows := make([]Asset, 0, len(files))
	for name, data := range files {
		rows = append(rows, Asset{Name: name, SHA256: digest(data)})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].Name < rows[j].Name })
	return rows
}
func sameAssetBytes(a, b namedBytes) bool {
	if len(a) != len(b) {
		return false
	}
	for n, d := range a {
		if !bytes.Equal(d, b[n]) {
			return false
		}
	}
	return true
}

func stageVerifiedAssets(files namedBytes, tag string) (string, error) {
	dir, err := os.MkdirTemp("", "markitect-release-upload-")
	if err != nil {
		return "", err
	}
	for _, name := range assetNames(tag) {
		data, ok := files[name]
		if !ok {
			os.RemoveAll(dir)
			return "", fmt.Errorf("verified payload %s is missing", name)
		}
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, data, 0600); err != nil {
			os.RemoveAll(dir)
			return "", err
		}
		readback, err := readLimited(path, 256<<20)
		if err != nil || !bytes.Equal(data, readback) {
			os.RemoveAll(dir)
			return "", fmt.Errorf("staged payload %s failed readback verification", name)
		}
	}
	return dir, nil
}

func splitHTTPResponse(data []byte) ([]byte, int, error) {
	lineEnd := bytes.IndexByte(data, '\n')
	if lineEnd < 0 {
		return nil, 0, errors.New("GitHub API response omitted an HTTP status line")
	}
	fields := strings.Fields(strings.TrimSpace(string(data[:lineEnd])))
	if len(fields) < 2 || !strings.HasPrefix(fields[0], "HTTP/") {
		return nil, 0, errors.New("GitHub API response has an invalid HTTP status line")
	}
	status, err := strconv.Atoi(fields[1])
	if err != nil {
		return nil, 0, errors.New("GitHub API response has an invalid HTTP status")
	}
	sep := bytes.Index(data, []byte("\r\n\r\n"))
	if sep >= 0 {
		return data[sep+4:], status, nil
	}
	sep = bytes.Index(data, []byte("\n\n"))
	if sep >= 0 {
		return data[sep+2:], status, nil
	}
	return nil, status, errors.New("GitHub API response omitted header/body separator")
}

func readLimited(name string, limit int64) ([]byte, error) {
	f, err := os.Open(name)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	data, err := io.ReadAll(io.LimitReader(f, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(data)) > limit {
		return nil, fmt.Errorf("%s exceeds size limit", name)
	}
	return data, nil
}
