// Package publish prepares and, when explicitly requested, publishes an
// immutable GitHub release for the fixed Markitect repository.
package publish

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/Glacius-Labs/Markitect/internal/release"
)

const repository = "Glacius-Labs/Markitect"
const workflowPath = ".github/workflows/release.yaml"

var semverTag = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$`)
var digestPattern = regexp.MustCompile(`^[0-9a-f]{64}$`)
var commitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)

var errDraftStillPending = errors.New("GitHub confirms the release is still a draft")

// Runner executes gh without taking or copying a credential. Production callers
// should inherit the authenticated environment established by gh auth login.
type Runner interface {
	Run(context.Context, string, ...string) ([]byte, error)
}

type Options struct {
	Tag       string
	RunID     string
	AssetsDir string
	Publish   bool
}

type Asset struct {
	Name   string `yaml:"name" json:"name"`
	SHA256 string `yaml:"sha256" json:"sha256"`
}

// Provenance is the strict metadata generated by the release workflow.
type Provenance struct {
	SchemaVersion      string  `yaml:"schemaVersion"`
	Tag                string  `yaml:"tag"`
	SourceCommit       string  `yaml:"sourceCommit"`
	WorkflowRunID      string  `yaml:"workflowRunId"`
	WorkflowRunAttempt string  `yaml:"workflowRunAttempt"`
	WorkflowRun        string  `yaml:"workflowRun"`
	Toolchain          string  `yaml:"toolchain"`
	Assets             []Asset `yaml:"assets"`
}

type Result struct {
	Status          string   `yaml:"status" json:"status"`
	Repository      string   `yaml:"repository" json:"repository"`
	Tag             string   `yaml:"tag" json:"tag"`
	SourceCommit    string   `yaml:"sourceCommit" json:"sourceCommit"`
	WorkflowRunID   string   `yaml:"workflowRunId" json:"workflowRunId"`
	WorkflowAttempt int      `yaml:"workflowRunAttempt" json:"workflowRunAttempt"`
	Version         string   `yaml:"version" json:"version"`
	Assets          []Asset  `yaml:"assets" json:"assets"`
	ReleaseID       int64    `yaml:"releaseId,omitempty" json:"releaseId,omitempty"`
	Immutable       bool     `yaml:"immutable,omitempty" json:"immutable,omitempty"`
	Steps           []string `yaml:"steps" json:"steps"`
}

type runInfo struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	Event      string `json:"event"`
	Status     string `json:"status"`
	Conclusion string `json:"conclusion"`
	HeadBranch string `json:"head_branch"`
	HeadSHA    string `json:"head_sha"`
	RunAttempt int    `json:"run_attempt"`
}

type artifactList struct {
	Artifacts []struct {
		Name        string `json:"name"`
		Expired     bool   `json:"expired"`
		WorkflowRun struct {
			ID int64 `json:"id"`
		} `json:"workflow_run"`
	} `json:"artifacts"`
}

type repoInfo struct {
	FullName    string `json:"full_name"`
	Permissions struct {
		Admin bool `json:"admin"`
	} `json:"permissions"`
}

type refInfo struct {
	Object struct {
		Type string `json:"type"`
		SHA  string `json:"sha"`
	} `json:"object"`
}
type tagInfo struct {
	Object struct {
		Type string `json:"type"`
		SHA  string `json:"sha"`
	} `json:"object"`
}
type releaseInfo struct {
	ID          int64         `json:"id"`
	TagName     string        `json:"tag_name"`
	Draft       bool          `json:"draft"`
	Immutable   bool          `json:"immutable"`
	PublishedAt string        `json:"published_at"`
	Assets      []remoteAsset `json:"assets"`
}
type remoteAsset struct {
	Name   string `json:"name"`
	Digest string `json:"digest"`
}

// Execute performs a complete read-only publication preflight by default.
// With Publish it repeats mutable remote checks before each state transition.
func Execute(ctx context.Context, runner Runner, options Options) (*Result, error) {
	if runner == nil {
		return nil, errors.New("GitHub command runner is required")
	}
	if !semverTag.MatchString(options.Tag) {
		return nil, fmt.Errorf("tag %q is not a supported vSemVer", options.Tag)
	}
	if options.RunID == "" {
		return nil, errors.New("workflow run ID is required")
	}
	if options.AssetsDir == "" {
		return nil, errors.New("local asset directory is required")
	}
	if _, err := strconv.ParseInt(options.RunID, 10, 64); err != nil {
		return nil, errors.New("workflow run ID must be numeric")
	}

	assets, err := readAssets(options.AssetsDir, options.Tag)
	if err != nil {
		return nil, err
	}
	result := &Result{Status: "preflight-passed", Repository: repository, Tag: options.Tag, Assets: assetRows(assets)}
	result.Steps = append(result.Steps, "publish operations are sequential, not transactional; any failure after draft creation leaves it for manual review")
	if err := call(runner, ctx, "", "auth", "status", "--hostname", "github.com"); err != nil {
		return nil, fmt.Errorf("gh auth status failed: %w", err)
	}
	result.Steps = append(result.Steps, "gh owner-authenticated session available")

	var repo repoInfo
	if err := apiJSON(runner, ctx, "repos/"+repository, &repo); err != nil {
		return nil, fmt.Errorf("read repository permissions: %w", err)
	}
	if repo.FullName != repository || !repo.Permissions.Admin {
		return nil, errors.New("authenticated gh user is not an administrator of the fixed repository")
	}
	var imm struct {
		Enabled bool `json:"enabled"`
	}
	if err := apiJSON(runner, ctx, "repos/"+repository+"/immutable-releases", &imm); err != nil {
		return nil, fmt.Errorf("read immutable-release setting: %w", err)
	}
	if !imm.Enabled {
		return nil, errors.New("GitHub immutable releases are not enabled")
	}
	result.Steps = append(result.Steps, "owner permission and immutable-release setting confirmed")

	runID, _ := strconv.ParseInt(options.RunID, 10, 64)
	var run runInfo
	if err := apiJSON(runner, ctx, fmt.Sprintf("repos/%s/actions/runs/%d", repository, runID), &run); err != nil {
		return nil, fmt.Errorf("read selected workflow run: %w", err)
	}
	path := strings.SplitN(run.Path, "@", 2)[0]
	if run.ID != runID || run.Status != "completed" || run.Conclusion != "success" || run.Event != "push" || path != workflowPath || run.HeadBranch != options.Tag || !commitPattern.MatchString(run.HeadSHA) || run.RunAttempt < 1 {
		return nil, errors.New("selected run is not a successful completed push of the fixed release workflow for this tag")
	}
	if err := validateTagTarget(runner, ctx, options.Tag, run.HeadSHA); err != nil {
		return nil, err
	}
	var artifacts artifactList
	if err := apiJSON(runner, ctx, fmt.Sprintf("repos/%s/actions/runs/%d/artifacts", repository, runID), &artifacts); err != nil {
		return nil, fmt.Errorf("read workflow artifacts: %w", err)
	}
	artifactName := "markitect-release-" + run.HeadSHA
	found := false
	for _, artifact := range artifacts.Artifacts {
		if artifact.Name == artifactName && !artifact.Expired && artifact.WorkflowRun.ID == runID {
			if found {
				return nil, errors.New("workflow run has duplicate release transport artifacts")
			}
			found = true
		}
	}
	if !found {
		return nil, fmt.Errorf("selected workflow run has no unexpired artifact %q", artifactName)
	}

	remoteAssets, err := downloadAndValidateArtifact(ctx, runner, options.RunID, artifactName, options.Tag, run)
	if err != nil {
		return nil, err
	}
	if !sameAssetBytes(assets, remoteAssets) {
		return nil, errors.New("local assets differ byte-for-byte from the selected successful workflow artifact")
	}
	result.SourceCommit = run.HeadSHA
	result.WorkflowRunID = options.RunID
	result.WorkflowAttempt = run.RunAttempt
	result.Version = strings.TrimPrefix(options.Tag, "v")
	result.Steps = append(result.Steps, "exact run-scoped artifact and all four local payload bytes verified")

	bundle := assets["markitect-"+options.Tag+"-bundle.zip"]
	parsedBundle, err := release.ParseBundle(bundle, digest(bundle))
	if err != nil {
		return nil, fmt.Errorf("release bundle validation failed: %w", err)
	}
	if parsedBundle.Manifest.Version != strings.TrimPrefix(options.Tag, "v") || parsedBundle.Manifest.SourceCommit != run.HeadSHA || parsedBundle.Manifest.SourceRepository != "github.com/Glacius-Labs/Markitect" {
		return nil, errors.New("bundle manifest version, source commit, or source repository does not match the selected release run")
	}
	result.Steps = append(result.Steps, "bundle manifest and four pinned files validate for the tagged version")
	if _, err := getRelease(runner, ctx, options.Tag); err == nil {
		return nil, fmt.Errorf("a GitHub release already exists for %s; existing drafts and releases are never replaced or resumed", options.Tag)
	} else if !isNotFound(err) {
		return nil, fmt.Errorf("could not safely check for an existing release: %w", err)
	}
	result.Steps = append(result.Steps, "no existing release or draft for tag")
	if !options.Publish {
		return result, nil
	}
	uploadDir, err := stageVerifiedAssets(assets, options.Tag)
	if err != nil {
		return nil, fmt.Errorf("stage verified release assets: %w", err)
	}
	defer os.RemoveAll(uploadDir)

	if err := validateTagTarget(runner, ctx, options.Tag, run.HeadSHA); err != nil {
		return nil, err
	}
	if err := checkImmutable(runner, ctx); err != nil {
		return nil, err
	}
	if _, err := getRelease(runner, ctx, options.Tag); err == nil {
		return nil, errors.New("release appeared after preflight; refusing to publish")
	} else if !isNotFound(err) {
		return nil, fmt.Errorf("recheck release name: %w", err)
	}
	draft, err := createDraft(runner, ctx, options.Tag, run.HeadSHA)
	if err != nil {
		return nil, fmt.Errorf("create empty draft failed (if the request reached GitHub, inspect the tag draft before retrying): %w", err)
	}
	result.ReleaseID = draft.ID
	result.Status = "draft-created"
	// Once a draft exists, failures intentionally leave it for manual review.
	// Re-running is rejected rather than attempting ambiguous resume semantics.
	assetPaths := make([]string, 0, len(assetNames(options.Tag)))
	for _, name := range assetNames(options.Tag) {
		assetPaths = append(assetPaths, filepath.Join(uploadDir, name))
	}
	args := []string{"release", "upload", options.Tag}
	args = append(args, assetPaths...)
	args = append(args, "--repo", "github.com/"+repository)
	if err := call(runner, ctx, "", args...); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; asset upload failed: %w", draft.ID, err)
	}
	if err := verifyDraftAssets(runner, ctx, draft.ID, assets); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; uploaded asset verification failed: %w", draft.ID, err)
	}
	if err := validateTagTarget(runner, ctx, options.Tag, run.HeadSHA); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; tag changed before publication: %w", draft.ID, err)
	}
	if err := checkImmutable(runner, ctx); err != nil {
		return result, fmt.Errorf("draft %d remains for manual review; immutable setting changed: %w", draft.ID, err)
	}
	if err := patchDraft(runner, ctx, draft.ID, options.Tag); err != nil {
		if errors.Is(err, errDraftStillPending) {
			result.Status = "draft-created"
			return result, fmt.Errorf("draft %d remains for manual review; GitHub confirmed it is still a draft: %w", draft.ID, err)
		}
		result.Status = "publication-unknown"
		return result, fmt.Errorf("publication outcome for release %d is unknown; inspect the tag and release state manually before retrying: %w", draft.ID, err)
	}
	result.Status = "published-verified"
	verificationSteps, err := verifyPublished(runner, ctx, options.Tag, run.HeadSHA, draft.ID, assets, uploadDir)
	if err != nil {
		result.Status = "published-unverified"
		return result, fmt.Errorf("release %d may be published but verification failed: %w", draft.ID, err)
	}
	result.Immutable = true
	result.Steps = append(result.Steps, verificationSteps...)
	result.Steps = append(result.Steps, "draft assets verified; release published immutable; release and each asset attestation verified; tag target rechecked")
	return result, nil
}
