package artifactcoverage

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/snapshot"
)

func TestCheckAccountsDerivedAndExplicitOwnershipAndFindsUntrackedFiles(t *testing.T) {
	root := t.TempDir()
	write(t, root, "markitect.yaml", `apiVersion: markitect.example.org/v1alpha1
kind: Project
metadata:
  name: sample
spec:
  targets: [markdown]
  areas:
    - name: general
      path: docs/general
`)
	write(t, root, "docs/general/rule.yaml", `apiVersion: markitect.example.org/v1alpha1
kind: Rule
metadata:
  name: policy
  namespace: general
spec:
  text: Keep policy explicit.
  files: [docs/general/reference.md]
`)
	write(t, root, "docs/general/skill.yaml", `apiVersion: markitect.example.org/v1alpha1
kind: Skill
metadata:
  name: entry
  namespace: general
spec:
  text: Follow the policy.
  rules:
    - name: policy
`)
	write(t, root, "docs/general/reference.md", "A declared opaque project input.\n")
	write(t, root, "docs/general/retained.md", "Reasoned exclusion.\n")
	for _, generated := range []string{
		"docs/markitect/README.md",
		"docs/markitect/general/README.md",
		"docs/markitect/general/rule.rule.md",
		"docs/markitect/general/skill.skill.md",
	} {
		write(t, root, generated, "<!-- Generated by Markitect; source: markitect.yaml -->\n")
	}
	write(t, root, "tools/check.go", "package tools\n")
	config := `apiVersion: markitect.example.org/artifact-coverage/v1alpha1
kind: ArtifactCoverage
spec:
  roots: [docs/general, docs/markitect, meta, tools]
  tooling:
    - path: meta/coverage.yaml
      owner: artifact coverage policy
    - path: tools/check.go
      owner: artifact coverage checker
  exclusions:
    - path: docs/general/retained.md
      reason: retained historical example awaiting migration
`
	write(t, root, "meta/coverage.yaml", config)

	report, err := Check(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if report.Status != "passed" {
		t.Fatalf("initial coverage failed: %#v", report.Findings)
	}
	classes := map[string]string{}
	for _, file := range report.Files {
		classes[file.Path] = file.Class
	}
	if classes["docs/general/skill.yaml"] != "canonical" || classes["docs/general/reference.md"] != "input" || classes["tools/check.go"] != "tooling" || classes["docs/general/retained.md"] != "excluded" {
		t.Fatalf("derived or explicit classes missing: %#v", classes)
	}
	if classes["docs/markitect/general/skill.skill.md"] != "generated" {
		t.Fatalf("renderer ownership missing: %#v", classes)
	}
	for _, file := range report.Files {
		if file.Path == "docs/general/retained.md" && file.Reason != "retained historical example awaiting migration" {
			t.Fatalf("exclusion reason not preserved: %#v", file)
		}
	}

	collision := strings.Replace(config,
		"    - path: tools/check.go\n",
		"    - path: docs/general/skill.yaml\n      owner: accidental second owner\n    - path: tools/check.go\n", 1)
	write(t, root, "meta/coverage.yaml", collision)
	report, err = Check(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !hasFinding(report, "ownership-collision", "docs/general/skill.yaml") {
		t.Fatalf("overlapping canonical/tooling ownership was not rejected: %#v", report.Findings)
	}
	generatedCollision := strings.Replace(config,
		"    - path: tools/check.go\n",
		"    - path: docs/markitect/general/skill.skill.md\n      owner: accidental generated owner\n    - path: tools/check.go\n", 1)
	write(t, root, "meta/coverage.yaml", generatedCollision)
	report, err = Check(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !hasFinding(report, "ownership-collision", "docs/markitect/general/skill.skill.md") {
		t.Fatalf("renderer/tooling ownership collision was not rejected: %#v", report.Findings)
	}
	write(t, root, "meta/coverage.yaml", config)
	if err := os.Chmod(filepath.Join(root, "tools/check.go"), 0755); err != nil {
		t.Fatal(err)
	}
	report, err = Check(root, "meta/coverage.yaml")
	if err != nil || report.Status != "passed" {
		t.Fatalf("executable tooling file should remain explicitly owned: err=%v findings=%#v", err, report.Findings)
	}
	if err := os.Rename(filepath.Join(root, "docs/general/reference.md"), filepath.Join(root, "docs/general/renamed-reference.md")); err != nil {
		t.Fatal(err)
	}
	report, err = Check(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !hasFindingMessage(report, "input.missing", "docs/general/reference.md") || !hasFinding(report, "unmanaged", "docs/general/renamed-reference.md") {
		t.Fatalf("renamed declared input was not reported as stale and unmanaged: %#v", report.Findings)
	}

	write(t, root, "docs/general/new-untracked.md", "Must be accounted for immediately.\n")
	report, err = Check(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !hasFinding(report, "unmanaged", "docs/general/new-untracked.md") {
		t.Fatalf("untracked managed file was not rejected: %#v", report.Findings)
	}
}

func TestCheckRejectsSymlinksWithinManagedRoots(t *testing.T) {
	root := t.TempDir()
	write(t, root, "markitect.yaml", "apiVersion: markitect.example.org/v1alpha1\nkind: Project\nmetadata:\n  name: sample\nspec: {}\n")
	write(t, root, "managed/owned.txt", "owned\n")
	write(t, root, "meta/coverage.yaml", `apiVersion: markitect.example.org/artifact-coverage/v1alpha1
kind: ArtifactCoverage
spec:
  roots: [managed, meta]
  tooling:
    - path: managed/owned.txt
      owner: owned helper
    - path: meta/coverage.yaml
      owner: coverage policy
`)
	if err := os.Symlink(filepath.Join(root, "managed/owned.txt"), filepath.Join(root, "managed/link.txt")); err != nil {
		t.Skipf("symlink creation is unavailable: %v", err)
	}
	if _, err := Check(root, "meta/coverage.yaml"); err == nil || !strings.Contains(err.Error(), "symlink or reparse point") {
		t.Fatalf("symlink in a managed tree was not rejected: %v", err)
	}
}

func TestConfigRejectsBroadAndAmbiguousExclusions(t *testing.T) {
	for _, entry := range []string{
		"{path: docs/**, reason: too broad}",
		"{path: docs\\general\\x.md, reason: nonportable spelling}",
		"{path: docs/general/x.md, reason: '   '}",
	} {
		text := "apiVersion: " + APIVersion + "\nkind: ArtifactCoverage\nspec:\n  roots: [docs]\n  exclusions:\n    - " + entry + "\n"
		config, err := ParseConfig([]byte(text))
		if err != nil {
			// Backslashes and malformed YAML can fail at the parser boundary.
			continue
		}
		if err := validateLiteralPath(config.Spec.Exclusions[0].Path); err == nil && config.Spec.Exclusions[0].Reason != "" && config.Spec.Exclusions[0].Reason != "   " {
			t.Fatalf("ambiguous exclusion accepted: %s", entry)
		}
	}
}

func TestOverlappingRootDiagnosticUsesDeclarationOrder(t *testing.T) {
	config := Config{Spec: ConfigSpec{Roots: []string{"managed/first", "managed/second", "managed"}}}
	snap := &snapshot.Snapshot{Files: map[string][]byte{}, Modes: map[string]string{}}
	root := t.TempDir()
	var first string
	for i := 0; i < 128; i++ {
		err := validateConfig(config, snap, root)
		if err == nil {
			t.Fatal("overlapping managed roots were accepted")
		}
		if i == 0 {
			first = err.Error()
			if !strings.Contains(first, `managed roots "managed/first" and "managed" overlap`) {
				t.Fatalf("overlap diagnostic did not select the first declared root: %s", first)
			}
			continue
		}
		if err.Error() != first {
			t.Fatalf("overlap diagnostic changed across repeated validation: first=%q later=%q", first, err.Error())
		}
	}
}

func TestCheckRejectsCaseAliasesInDeclarationsOnEveryHost(t *testing.T) {
	root := t.TempDir()
	write(t, root, "markitect.yaml", "apiVersion: markitect.example.org/v1alpha1\nkind: Project\nmetadata:\n  name: sample\nspec: {}\n")
	write(t, root, "managed/entry.txt", "managed\n")
	write(t, root, "meta/coverage.yaml", `apiVersion: markitect.example.org/artifact-coverage/v1alpha1
kind: ArtifactCoverage
spec:
  roots: [managed, meta]
  tooling:
    - path: meta/Coverage.yaml
      owner: artifact coverage policy
`)
	_, err := Check(root, "meta/coverage.yaml")
	if err == nil || !strings.Contains(err.Error(), "case-insensitive path collision") {
		t.Fatalf("case alias was not rejected portably: %v", err)
	}
}

func TestCheckFindsStaleDeclarationsAndOrphanGeneratedOutput(t *testing.T) {
	root := t.TempDir()
	write(t, root, "markitect.yaml", "apiVersion: markitect.example.org/v1alpha1\nkind: Project\nmetadata:\n  name: sample\nspec: {}\n")
	write(t, root, "managed/orphan.md", "<!-- Generated by Markitect; source: deleted.yaml -->\nold output\n")
	write(t, root, "managed/orphan.toml", "# Generated by Markitect; source: deleted.toml\nold output\n")
	write(t, root, "managed/schema/Project.yaml", "# Generated by Markitect; edit Go validation declarations.\n$schema: https://json-schema.org/draft/2020-12/schema\n")
	write(t, root, "managed/schema/Workflow.yaml", "# Generated by Markitect; edit Go validation declarations.\n$schema: https://json-schema.org/draft/2020-12/schema\n")
	write(t, root, "managed/schema/unknown.yaml", "# Generated by Markitect; unrelated generator output.\n")
	write(t, root, "managed/obsolete.txt", "old tool\n")
	write(t, root, "meta/coverage.yaml", `apiVersion: markitect.example.org/artifact-coverage/v1alpha1
kind: ArtifactCoverage
spec:
  roots: [managed, meta]
  tooling:
    - path: meta/coverage.yaml
      owner: artifact coverage policy
    - path: managed/schema/Project.yaml
      owner: project schema generator
    - path: managed/obsolete.txt
      owner: removed tool
  exclusions:
    - path: managed/deleted.txt
      reason: old exception
    - path: managed/schema/Workflow.yaml
      reason: schema produced by an external release task
`)
	report, err := Check(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range [][2]string{{"orphan-generated", "managed/orphan.md"}, {"orphan-generated", "managed/orphan.toml"}, {"stale-exclusion", "managed/deleted.txt"}, {"unmanaged", "managed/schema/unknown.yaml"}} {
		if !hasFinding(report, expected[0], expected[1]) {
			t.Errorf("missing %s for %s: %#v", expected[0], expected[1], report.Findings)
		}
	}
	if !hasClass(report, "managed/schema/Project.yaml", "tooling") || !hasClass(report, "managed/schema/Workflow.yaml", "excluded") {
		t.Fatalf("non-renderer generated schema files were not accounted for: %#v", report.Files)
	}
	if err := os.Remove(filepath.Join(root, "managed/obsolete.txt")); err != nil {
		t.Fatal(err)
	}
	report, err = Check(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !hasFinding(report, "stale-tooling", "managed/obsolete.txt") {
		t.Fatalf("deleted tooling declaration was not reported: %#v", report.Findings)
	}
}

func hasFinding(report Report, code, name string) bool {
	for _, finding := range report.Findings {
		if finding.Code == code && finding.Path == name {
			return true
		}
	}
	return false
}

func hasClass(report Report, name, class string) bool {
	for _, file := range report.Files {
		if file.Path == name && file.Class == class {
			return true
		}
	}
	return false
}

func hasFindingMessage(report Report, code, text string) bool {
	for _, finding := range report.Findings {
		if finding.Code == code && strings.Contains(finding.Message, text) {
			return true
		}
	}
	return false
}

func write(t *testing.T, root, name, contents string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(contents), 0644); err != nil {
		t.Fatal(err)
	}
}
