package main

import (
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/host"
	"github.com/Glacius-Labs/Markitect/internal/infrastructure/source"
)

func TestInventoryDoesNotInferResourceKindsFromDirectoryNames(t *testing.T) {
	root := t.TempDir()
	writeRepoFile(t, root, "README.md", []byte("Project navigation.\n"))
	writeRepoFile(t, root, "handbook/rules/change.md", []byte("Ordinary prose.\n"))
	writeRepoFile(t, root, "handbook/generated.md", []byte("<!-- Generated by Markitect; source: handbook/change.yaml -->\n"))
	code, output, stderr := invoke("inventory", "--repo", root)
	if code != 0 {
		t.Fatalf("inventory exit=%d stderr=%s output=%s", code, stderr, output)
	}
	result := decodeYAML[report](t, output)
	if len(result.Inventory) != 2 || result.Inventory[0].Path != "README.md" || result.Inventory[1].Path != "handbook/rules/change.md" {
		t.Fatalf("inventory missed ordinary Markdown or included generated output: %#v", result.Inventory)
	}
	for _, entry := range result.Inventory {
		if entry.Kind != "Markdown" {
			t.Fatalf("directory name inferred typed resource ownership: %#v", entry)
		}
	}
}

func TestContextIncludesSnapshotDigestAndRequiredRule(t *testing.T) {
	repo := newCLIRepo(t, false)
	code, output, stderr := invoke("context", "--repo", repo.root, "--revision", repo.base, "--kind", "Skill", "--name", "entry", "--namespace", cliNamespace)
	if code != 0 {
		t.Fatalf("context exit=%d stderr=%s output=%s", code, stderr, output)
	}
	ctx := decodeYAML[host.Context](t, output)
	snapshot, err := source.Load(repo.root, repo.base)
	if err != nil {
		t.Fatal(err)
	}
	if ctx.SnapshotDigest == "" || ctx.SnapshotDigest != snapshot.Digest() || ctx.ToolDigest == "" || ctx.Provisional || ctx.Revision != repo.base {
		t.Fatalf("context has incorrect snapshot identity: %#v, actual digest %s", ctx, snapshot.Digest())
	}
	foundRule := false
	for _, input := range ctx.Inputs {
		if input.Resource != nil && input.Resource.Kind == "Rule" && input.Resource.Metadata.Name == "policy" {
			foundRule = true
			if input.Hash != host.Hash(snapshot.Files[input.Path]) {
				t.Errorf("rule input hash %s does not match snapshot bytes", input.Key)
			}
		}
	}
	if !foundRule {
		t.Fatalf("context omitted the required Rule: %#v", ctx.Inputs)
	}
}
