package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/Glacius-Labs/Markitect/internal/app"
	"github.com/Glacius-Labs/Markitect/internal/authoring"
	"github.com/Glacius-Labs/Markitect/internal/format"
)

func runAuthoring(o commandOptions, errout io.Writer, emit func(any) int, fail func(error) int) int {
	if o.flagCount != 0 {
		fmt.Fprintln(errout, "authoring accepts no flags; its compiled context has no repository or revision")
		return 2
	}
	digest, err := currentToolDigest()
	if err != nil {
		return fail(err)
	}
	ctx, err := authoring.Context(version, digest)
	if err != nil {
		return fail(err)
	}
	return emit(ctx)
}

func runSchema(o commandOptions, errout io.Writer, emit func(any) int, fail func(error) int) int {
	schemas, err := format.Schemas()
	if err != nil {
		return fail(err)
	}
	for name, data := range schemas {
		target := filepath.Join(o.root, filepath.FromSlash(name))
		data = append([]byte("# Generated by Markitect; edit Go validation declarations.\n"), data...)
		schemas[name] = data
		if !o.write {
			existing, err := os.ReadFile(target)
			if err != nil || string(existing) != string(data) {
				fmt.Fprintln(errout, "schema drift:", name)
				return 1
			}
		}
	}
	if o.write {
		if err = app.WriteSchemas(o.root, schemas); err != nil {
			return fail(err)
		}
	}
	return emit(map[string]any{"status": "passed", "schemas": len(schemas), "version": version})
}
