package artifactcoverage

import (
	"strings"
	"testing"
)

func TestCheckAccountsSuppliedOwnershipAndNewFiles(t *testing.T) {
	config, inventory := fixture()
	inventory.InputOwners = append(inventory.InputOwners, OwnerFact{Path: "content/reference.md", Owner: "general/Skill/another"})
	report, err := Check(config, inventory)
	if err != nil {
		t.Fatal(err)
	}
	if report.Status != "passed" || report.SnapshotDigest != inventory.SnapshotDigest {
		t.Fatalf("unexpected report: %#v", report)
	}
	for _, expected := range [][2]string{{"content/canonical.yaml", "canonical"}, {"content/reference.md", "input"}, {"generated/entry.md", "generated"}, {"tools/check.go", "tooling"}, {"content/retained.md", "excluded"}} {
		if !hasClass(report, expected[0], expected[1]) {
			t.Errorf("missing %s classification for %s", expected[1], expected[0])
		}
	}
	if got := strings.Join(ownersFor(report, "content/reference.md"), ","); got != "general/Rule/policy,general/Skill/another" {
		t.Fatalf("shared input consumers = %q", got)
	}
	if got := reasonFor(report, "content/retained.md"); got != "retained historical fixture" {
		t.Fatalf("exclusion reason = %q", got)
	}

	inventory.Files["content/new.md"] = []byte("new and unowned\n")
	report, err = Check(config, inventory)
	if err != nil {
		t.Fatal(err)
	}
	if !hasFinding(report, "unmanaged", "content/new.md") {
		t.Fatalf("new file was not reported: %#v", report.Findings)
	}
}

func TestCheckReportsDeletedInputAndRenamedFile(t *testing.T) {
	config, inventory := fixture()
	delete(inventory.Files, "content/reference.md")
	inventory.Files["content/renamed-reference.md"] = []byte("renamed\n")
	report, err := Check(config, inventory)
	if err != nil {
		t.Fatal(err)
	}
	if !hasFinding(report, "input.missing", "content/reference.md") || !hasFinding(report, "unmanaged", "content/renamed-reference.md") {
		t.Fatalf("missing deleted/renamed input findings: %#v", report.Findings)
	}
}

func TestCheckSeparatesRendererMarkersFromOtherGenerators(t *testing.T) {
	config, inventory := fixture()
	inventory.Files["generated/orphan.md"] = []byte("<!-- Generated by Markitect; source: deleted.yaml -->\n")
	inventory.Files["generated/orphan.toml"] = []byte("# Generated by Markitect; source: deleted.toml\n")
	inventory.Files["tools/schema.yaml"] = []byte("# Generated by Markitect; edit Go validation declarations.\n")
	inventory.Files["tools/external-schema.yaml"] = []byte("# Generated by Markitect; external generator output.\n")
	inventory.Files["tools/unknown-schema.yaml"] = []byte("# Generated by Markitect; unknown generator output.\n")
	config.Spec.Tooling = append(config.Spec.Tooling, ToolOwner{Path: "tools/schema.yaml", Owner: "schema generator"})
	config.Spec.Exclusions = append(config.Spec.Exclusions, Exclusion{Path: "tools/external-schema.yaml", Reason: "produced by a separate schema release task"})
	report, err := Check(config, inventory)
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{"generated/orphan.md", "generated/orphan.toml"} {
		if !hasFinding(report, "orphan-generated", path) {
			t.Errorf("renderer projection %s was not reported orphaned", path)
		}
	}
	if !hasClass(report, "tools/schema.yaml", "tooling") || !hasClass(report, "tools/external-schema.yaml", "excluded") {
		t.Fatalf("other generator ownership was lost: %#v", report.Files)
	}
	if !hasFinding(report, "unmanaged", "tools/unknown-schema.yaml") {
		t.Fatalf("unknown marked YAML was not unmanaged: %#v", report.Findings)
	}
}

func TestCheckReportsGeneratedMissingAndToolingCollision(t *testing.T) {
	config, inventory := fixture()
	config.Spec.Tooling = append(config.Spec.Tooling, ToolOwner{Path: "generated/entry.md", Owner: "second owner"})
	inventory.GeneratedOwners = append(inventory.GeneratedOwners, OwnerFact{Path: "generated/missing.md", Owner: "general/Skill/missing"})
	report, err := Check(config, inventory)
	if err != nil {
		t.Fatal(err)
	}
	if !hasFinding(report, "ownership-collision", "generated/entry.md") || !hasFinding(report, "missing-generated", "generated/missing.md") {
		t.Fatalf("generated owner findings missing: %#v", report.Findings)
	}
}

func TestCheckRejectsInvalidExclusionAndPortableAliases(t *testing.T) {
	config, inventory := fixture()
	config.Spec.Exclusions = append(config.Spec.Exclusions, Exclusion{Path: "content/**", Reason: "too broad"})
	if _, err := Check(config, inventory); err == nil || !strings.Contains(err.Error(), "invalid exclusion path") {
		t.Fatalf("broad exclusion accepted: %v", err)
	}

	config, inventory = fixture()
	inventory.Files["content/Reference.md"] = []byte("case alias\n")
	if _, err := Check(config, inventory); err == nil || !strings.Contains(err.Error(), "case-insensitive path collision") {
		t.Fatalf("case alias accepted: %v", err)
	}

	config, inventory = fixture()
	inventory.InputOwners = append(inventory.InputOwners, OwnerFact{Path: "content/Reference.md", Owner: "general/Rule/alias"})
	if _, err := Check(config, inventory); err == nil || !strings.Contains(err.Error(), "case-insensitive path collision") {
		t.Fatalf("ownership fact case alias accepted: %v", err)
	}

	config, inventory = fixture()
	config.Spec.Tooling = append(config.Spec.Tooling, ToolOwner{Path: "tools/CON.txt", Owner: "invalid Windows path"})
	if _, err := Check(config, inventory); err == nil || !strings.Contains(err.Error(), "Windows device name") {
		t.Fatalf("Windows device name accepted: %v", err)
	}
}

func TestCheckReportOrderIsDeterministic(t *testing.T) {
	config, inventory := fixture()
	inventory.Files["content/zeta.txt"] = []byte("z\n")
	inventory.Files["content/alpha.txt"] = []byte("a\n")
	first, err := Check(config, inventory)
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 64; i++ {
		report, err := Check(config, inventory)
		if err != nil {
			t.Fatal(err)
		}
		if len(report.Findings) != len(first.Findings) || len(report.Files) != len(first.Files) {
			t.Fatalf("report size changed across runs: first=%#v current=%#v", first, report)
		}
		for j := range first.Findings {
			if first.Findings[j] != report.Findings[j] {
				t.Fatalf("finding order changed: first=%#v current=%#v", first.Findings, report.Findings)
			}
		}
		for j := range first.Files {
			if first.Files[j].Path != report.Files[j].Path || first.Files[j].Class != report.Files[j].Class {
				t.Fatalf("file order changed: first=%#v current=%#v", first.Files, report.Files)
			}
		}
	}
}

func TestParseConfigIsClosedAndVersioned(t *testing.T) {
	data := []byte("apiVersion: " + APIVersion + "\nkind: ArtifactCoverage\nspec:\n  roots: [content]\n  unknown: value\n")
	if _, err := ParseConfig(data); err == nil {
		t.Fatal("unknown config field was accepted")
	}
	if _, err := ParseConfig([]byte("apiVersion: wrong\nkind: ArtifactCoverage\nspec: {roots: [content]}\n")); err == nil {
		t.Fatal("wrong config version was accepted")
	}
}

func fixture() (Config, Inventory) {
	configPath := "meta/markitect-artifacts.yaml"
	config := Config{
		APIVersion: APIVersion,
		Kind:       "ArtifactCoverage",
		SourcePath: configPath,
		Spec: ConfigSpec{
			Roots: []string{"content", "generated", "meta", "tools"},
			Tooling: []ToolOwner{
				{Path: configPath, Owner: "artifact coverage policy"},
				{Path: "tools/check.go", Owner: "artifact coverage checker"},
			},
			Exclusions: []Exclusion{{Path: "content/retained.md", Reason: "retained historical fixture"}},
		},
	}
	inventory := Inventory{
		SnapshotDigest: "sha256:fixed-fixture",
		Files: map[string][]byte{
			"content/canonical.yaml":        []byte("kind: Rule\n"),
			"content/reference.md":          []byte("opaque input\n"),
			"content/retained.md":           []byte("excluded content\n"),
			"generated/entry.md":            []byte("<!-- Generated by Markitect; source: content/canonical.yaml -->\n"),
			"meta/markitect-artifacts.yaml": []byte("versioned config bytes\n"),
			"tools/check.go":                []byte("package check\n"),
		},
		CanonicalOwners: []OwnerFact{{Path: "content/canonical.yaml", Owner: "general/Rule/policy"}},
		InputOwners:     []OwnerFact{{Path: "content/reference.md", Owner: "general/Rule/policy"}},
		GeneratedOwners: []OwnerFact{{Path: "generated/entry.md", Owner: "general/Skill/entry"}},
	}
	return config, inventory
}

func hasFinding(report Report, code, name string) bool {
	for _, finding := range report.Findings {
		if finding.Code == code && finding.Path == name {
			return true
		}
	}
	return false
}

func hasClass(report Report, name, class string) bool {
	for _, file := range report.Files {
		if file.Path == name && file.Class == class {
			return true
		}
	}
	return false
}

func ownersFor(report Report, name string) []string {
	for _, file := range report.Files {
		if file.Path == name {
			return file.Owners
		}
	}
	return nil
}

func reasonFor(report Report, name string) string {
	for _, file := range report.Files {
		if file.Path == name {
			return file.Reason
		}
	}
	return ""
}
