package projectwork

import (
	"bytes"
	"fmt"
	"io/fs"
	"path"
	"sort"
	"strings"

	hostwrite "github.com/Glacius-Labs/Markitect/internal/host"
	"github.com/Glacius-Labs/Markitect/internal/modules/projectmodel"
)

const ViewPath = ".markitect/views/project.md"
const generatedViewMarker = "<!-- Generated by Markitect projectwork; edit selected model sources instead. -->"

// Document renders a readable view with desired requirements, observed files,
// and declared checks in separate sections.
func Document(project *Project, write bool) (string, error) {
	if project == nil || project.Snapshot == nil {
		return "", fmt.Errorf("project snapshot is required")
	}
	content := documentText(project)
	if !write {
		return content, nil
	}
	if err := writeDocument(project, content); err != nil {
		return content, err
	}
	return content, nil
}

func writeDocument(project *Project, content string) error {
	if !project.Provisional {
		return fmt.Errorf("writing a view requires a provisional current-working-tree Project")
	}
	current, err := Load(project.Root, "")
	if err != nil {
		return err
	}
	if current.Digest != project.Digest {
		return fmt.Errorf("project changed after the view was prepared")
	}
	paths := make([]string, 0, len(current.Snapshot.Files)+1)
	for file := range current.Snapshot.Files {
		paths = append(paths, file)
	}
	paths = append(paths, ViewPath)
	paths = uniqueSorted(paths)
	capture, err := hostwrite.CaptureGuardedWrite(project.Root, paths)
	if err != nil {
		return fmt.Errorf("capture generated project view: %w", err)
	}
	for file, data := range current.Snapshot.Files {
		actual, ok := capture.Files[file]
		if !ok || !actual.Exists || !bytes.Equal(actual.Bytes, data) || !sameSnapshotMode(actual.Mode, current.Snapshot.Modes[file]) {
			return fmt.Errorf("selected Project input changed before writing the view: %s", file)
		}
	}
	if existing, ok := capture.Files[ViewPath]; ok && existing.Exists && !bytes.Contains(existing.Bytes, []byte(generatedViewMarker)) {
		return fmt.Errorf("refusing to replace non-generated file at %s", ViewPath)
	}
	validate := func() error {
		var current *Project
		var loadErr error
		if project.Provisional {
			current, loadErr = Load(project.Root, "")
		} else {
			current, loadErr = Load(project.Root, project.Revision)
		}
		if loadErr != nil {
			return loadErr
		}
		if current.Digest != project.Digest {
			return fmt.Errorf("selected project inputs changed before document write")
		}
		return nil
	}
	_, err = hostwrite.ApplyGuardedWriteChecked(capture.Root, capture, []hostwrite.GuardedWriteChange{{Path: ViewPath, Bytes: []byte(content), Mode: fs.FileMode(0644)}}, validate)
	if err != nil {
		return fmt.Errorf("write generated view %s: %w", ViewPath, err)
	}
	return nil
}

func documentText(project *Project) string {
	var out strings.Builder
	fmt.Fprintf(&out, "%s\n\n# %s\n\n", generatedViewMarker, heading(project.Config.Name))
	if project.Provisional {
		out.WriteString("Source: provisional working-tree snapshot\n\n")
	} else {
		fmt.Fprintf(&out, "Source revision: %s\n\n", project.Revision)
	}
	fmt.Fprintf(&out, "Project binding: %s  \nModel digest: %s  \nReport status: %s\n\n", project.Digest, project.Model.Digest, project.Report.Status)
	out.WriteString("The structural model compiled from the explicitly selected Definition files. This view does not establish that repository code, tests, or prose conform to the model. Declared checks are not evidence that they ran.\n\n")

	out.WriteString("## Responsibilities\n\n")
	managers := append([]projectmodel.Manager(nil), project.Report.Managers...)
	sort.Slice(managers, func(i, j int) bool { return managers[i].ID < managers[j].ID })
	if len(managers) == 0 {
		out.WriteString("No Manager definitions are selected.\n\n")
	} else {
		for _, manager := range managers {
			fmt.Fprintf(&out, "### %s\n\n- Identity: %s\n- Namespace: %s\n", heading(manager.Name), manager.ID, manager.Namespace)
			if manager.Purpose != "" {
				fmt.Fprintf(&out, "- Purpose: %s\n", inline(manager.Purpose))
			}
			if manager.Parent != "" {
				fmt.Fprintf(&out, "- Parent Manager: %s\n", manager.Parent)
			}
			if len(manager.Owns) > 0 {
				fmt.Fprintf(&out, "- Delegated paths: %s\n", list(manager.Owns))
			}
			if manager.Instructions != "" {
				fmt.Fprintf(&out, "- Instructions: %s\n", inline(manager.Instructions))
			}
			out.WriteString("\n")
		}
	}

	out.WriteString("## Statements\n\n")
	statements := append([]projectmodel.Statement(nil), project.Report.Statements...)
	sort.Slice(statements, func(i, j int) bool { return statements[i].ID < statements[j].ID })
	if len(statements) == 0 {
		out.WriteString("No Statements are selected.\n\n")
	} else {
		for _, statement := range statements {
			fmt.Fprintf(&out, "### %s\n\n- Identity: %s\n- Category: %s\n- Responsible Manager: %s\n- Source: %s\n\n%s\n\n",
				heading(statement.Name), statement.ID, inline(statement.Category), statement.Owner, sourceLink(statement.Source), inline(statement.Description))
			if len(statement.Requires) > 0 {
				fmt.Fprintf(&out, "Requires: %s\n\n", list(statement.Requires))
			}
			if len(statement.Uses) > 0 {
				fmt.Fprintf(&out, "Uses: %s\n\n", list(statement.Uses))
			}
		}
	}

	out.WriteString("## Expected artifacts\n\n")
	artifacts := append([]projectmodel.Artifact(nil), project.Report.Artifacts...)
	sort.Slice(artifacts, func(i, j int) bool { return artifacts[i].ID < artifacts[j].ID })
	if len(artifacts) == 0 {
		out.WriteString("No Artifact expectations are selected.\n\n")
	} else {
		for _, artifact := range artifacts {
			requirement := "optional"
			if artifact.Required {
				requirement = "required"
			}
			fmt.Fprintf(&out, "### %s\n\n- Identity: %s\n- Requirement: %s\n- Role: %s\n- Responsible Manager: %s\n",
				heading(artifact.Name), artifact.ID, requirement, inline(artifact.Role), artifact.Owner)
			if len(artifact.Realizes) > 0 {
				fmt.Fprintf(&out, "- Realizes: %s\n", list(artifact.Realizes))
			}
			if len(artifact.Paths) > 0 {
				fmt.Fprintf(&out, "- Expected paths: %s\n", pathList(artifact.Paths))
			} else {
				out.WriteString("- Expected paths: not assigned\n")
			}
			if len(artifact.Checks) > 0 {
				fmt.Fprintf(&out, "- Related checks: %s (declared; execution not observed)\n", list(artifact.Checks))
			} else {
				out.WriteString("- Related checks: none declared\n")
			}
			if artifact.Reason != "" {
				fmt.Fprintf(&out, "- Applicability: %s\n", inline(artifact.Reason))
			}
			out.WriteString("\n")
		}
	}

	out.WriteString("## Observed inventory\n\n")
	observed := append([]projectmodel.FileEntry(nil), project.Report.Files...)
	sort.Slice(observed, func(i, j int) bool { return observed[i].Path < observed[j].Path })
	if len(observed) == 0 {
		out.WriteString("No files were supplied by the selected inventory roots. This does not mean that the repository contains no files.\n\n")
	} else {
		out.WriteString("| Path | Observation | Responsible Manager | Class | Coverage |\n|---|---|---|---|---|\n")
		for _, file := range observed {
			observation := "not present"
			if file.Exists {
				observation = "present"
			}
			coverage := "unmodeled: no Artifact path declared"
			if len(file.Artifacts) > 0 {
				coverage = "linked to an expected Artifact"
			}
			fmt.Fprintf(&out, "| %s | %s | %s | %s | %s |\n", sourceLink(file.Path), observation, inline(file.Owner), inline(file.Class), coverage)
		}
		out.WriteString("\n")
	}

	out.WriteString("## Declared checks\n\n")
	checks := append([]projectmodel.Check(nil), project.Report.Checks...)
	sort.Slice(checks, func(i, j int) bool { return checks[i].ID < checks[j].ID })
	if len(checks) == 0 {
		out.WriteString("No checks are declared.\n\n")
	} else {
		for _, check := range checks {
			fmt.Fprintf(&out, "- %s (%s), owned by %s: %s — declared only; no run result is bound to this report.\n",
				inline(check.Name), check.ID, inline(check.Owner), shellDisplay(check.Command))
			if check.Limitation != "" {
				fmt.Fprintf(&out, "  - Limit: %s\n", inline(check.Limitation))
			}
		}
		out.WriteString("\n")
	}

	out.WriteString("## Coverage and findings\n\n")
	if len(project.Report.Unknown) == 0 {
		out.WriteString("No unowned inventory paths were reported. Per-file Artifact coverage is shown above.\n\n")
	} else {
		for _, unknown := range project.Report.Unknown {
			fmt.Fprintf(&out, "- Unknown: %s\n", inline(unknown))
		}
		out.WriteString("\n")
	}
	findings := append([]projectmodel.Finding(nil), project.Report.Findings...)
	sort.Slice(findings, func(i, j int) bool {
		if findings[i].Code != findings[j].Code {
			return findings[i].Code < findings[j].Code
		}
		return findings[i].Subject < findings[j].Subject
	})
	if len(findings) == 0 {
		out.WriteString("No structural or coverage findings were reported.\n")
	} else {
		for _, finding := range findings {
			fmt.Fprintf(&out, "- %s (%s, %s): %s\n", inline(finding.Severity), inline(finding.Code), inline(finding.Subject), inline(finding.Message))
		}
	}
	return out.String()
}

func heading(value string) string { return strings.TrimSpace(strings.ReplaceAll(value, "\n", " ")) }
func inline(value string) string {
	return strings.NewReplacer("\r", " ", "\n", " ", "|", "\\|").Replace(value)
}

func list(values []string) string {
	copyValues := append([]string(nil), values...)
	sort.Strings(copyValues)
	for i, value := range copyValues {
		copyValues[i] = inline(value)
	}
	return strings.Join(copyValues, ", ")
}

func pathList(values []string) string {
	copyValues := append([]string(nil), values...)
	sort.Strings(copyValues)
	for i, value := range copyValues {
		copyValues[i] = sourceLink(value)
	}
	return strings.Join(copyValues, ", ")
}

func sourceLink(value string) string {
	clean := path.Clean(strings.TrimPrefix(value, "/"))
	if clean == "." || strings.HasPrefix(clean, "../") || strings.Contains(clean, "\\") {
		return inline(value)
	}
	relative := "../../" + clean
	if strings.HasPrefix(clean, ".markitect/model/") {
		relative = "../model/" + strings.TrimPrefix(clean, ".markitect/model/")
	}
	return "[" + inline(value) + "](" + strings.ReplaceAll(relative, " ", "%20") + ")"
}

func shellDisplay(command []string) string {
	if len(command) == 0 {
		return "(empty command)"
	}
	return strings.Join(command, " ")
}
