// Package agentrules projects normalized Agent, Skill, and Rule resources into
// explicitly selected Codex and Claude entrypoints. It has no filesystem or
// authoring-YAML access; Host supplies the validated model, resolved mappings,
// provider settings, and exact snapshot bytes.
package agentrules

import (
	"strings"

	core "github.com/Glacius-Labs/Markitect/src/internal/host/compat/v0_13/kernel"
)

const Marker = "Generated by Markitect"

// MarkitectAIVersion identifies the built-in vocabulary whose Agent, Skill,
// and Rule kinds have provider-entrypoint semantics. Domain-defined resources
// may use the same kind names without acquiring those semantics.
const MarkitectAIVersion = core.APIVersion

// Config is the Agent Rules module's normalized view of Host-owned project
// settings. RuleKeys are resolved Core identity keys; settings are derived from
// the canonical Agent source and are never read from another provider output.
type Config struct {
	Targets          []string
	ProjectKey       string
	ProjectPath      string
	RuleAdapters     []RuleAdapter
	ProviderAdapters ProviderAdapters
	AgentSettings    map[string]AgentSettings
	PackageVersions  map[string]string
}

type RuleAdapter struct {
	Name     string
	RuleKeys []string
}

type ProviderAdapters struct {
	AgentContract     string
	RoleRegister      string
	InlineAgentText   bool
	StrictInventory   bool
	ClaudeRuleSources map[string][]string
	RetiredSkills     []string
	RetiredAgents     []string
}

type AgentSettings struct {
	Codex  *CodexSettings
	Claude *ClaudeSettings
}

type CodexSettings struct {
	Model   string
	Effort  string
	Sandbox string
}

type ClaudeSettings struct {
	Model           string
	Effort          string
	PermissionMode  string
	Tools           []string
	DisallowedTools []string
	MaxTurns        int
}

// Generate deterministically returns generated repository-relative files and
// their canonical Core identity owners. Only explicitly selected targets are
// emitted. Any invalid module configuration or collision fails closed.
func Generate(model core.SemanticModel, config Config, files map[string][]byte) (map[string][]byte, map[string][]string, error) {
	return generate(model, config, files)
}

// OutputPaths returns selected generated paths and their canonical Core
// owners. The plan is independent of source bytes and module findings.
func OutputPaths(model core.SemanticModel, config Config) (map[string][]string, error) {
	plan, err := buildPlan(model, config)
	if err != nil {
		return nil, err
	}
	paths := make(map[string][]string, len(plan.paths))
	for path, owners := range plan.paths {
		paths[path] = append([]string(nil), owners...)
	}
	return paths, nil
}

// Validate checks Agent Rules configuration and its exact declared source
// bytes without reading the filesystem. Generated-output ownership is derived
// from the same deterministic projection used by Generate.
func Validate(model core.SemanticModel, config Config, files map[string][]byte) []core.Diagnostic {
	plan, err := buildPlan(model, config)
	if err != nil {
		return []core.Diagnostic{{Code: "agent-rules.output-plan", Path: config.ProjectPath, Message: err.Error()}}
	}
	diagnostics := validateNormalizedConfig(config, plan.local, plan.byKey)
	diagnostics = append(diagnostics, validateAdapters(config, files, plan.paths)...)
	sortDiagnostics(diagnostics)
	return diagnostics
}

func activeTarget(config Config, target string) bool {
	for _, selected := range config.Targets {
		if selected == target {
			return true
		}
	}
	return false
}

func hasProviderTarget(config Config) bool {
	return activeTarget(config, "codex") || activeTarget(config, "claude")
}

func isMarkitectAIResource(resource core.ModelResource) bool {
	return resource.Identity.APIVersion == MarkitectAIVersion
}

func diagnostic(code, file string, line int, message string) core.Diagnostic {
	return core.Diagnostic{Code: code, Path: file, Line: line, Message: message}
}

// IsGenerated recognizes the ownership marker emitted by this module. It is
// used only to avoid treating a previously generated companion as prose input.
func IsGenerated(data []byte) bool {
	text := strings.TrimSpace(string(data))
	if strings.HasPrefix(text, "---\n") || strings.HasPrefix(text, "---\r\n") {
		lines := strings.Split(text, "\n")
		closed := false
		for i := 1; i < len(lines); i++ {
			if strings.TrimSpace(lines[i]) == "---" {
				text = strings.TrimSpace(strings.Join(lines[i+1:], "\n"))
				closed = true
				break
			}
		}
		if !closed {
			return false
		}
	}
	return strings.HasPrefix(text, "<!-- Generated by Markitect;") || strings.HasPrefix(text, "# Generated by Markitect;") || strings.HasPrefix(text, "<!-- Generated by Markitect -->")
}
