package app

import (
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/render"
)

func TestCheckOutputsDoesNotTreatGeneratedSchemaYAMLAsOwnedOutput(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := render.Generate(p.Graph, p.Snapshot.Files)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range generated {
		snapshot.Files[name] = append([]byte(nil), data...)
		snapshot.Modes[name] = "100644"
	}

	const schemaPath = "schema/Text.yaml"
	snapshot.Files[schemaPath] = []byte("# Generated by Markitect; schema resource\ntype: object\n")
	snapshot.Modes[schemaPath] = "100644"
	if !Generated(snapshot.Files[schemaPath]) {
		t.Fatal("test setup: schema fixture is not marked as generated")
	}

	p, err = Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	if findings := CheckOutputs(p); len(findings) != 0 {
		t.Fatalf("generated schema YAML was treated as a Markitect-owned or stale output: %#v", findings)
	}
}

func TestCheckOutputsRejectsOrphanedAggregateRuleAdapter(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := render.Generate(p.Graph, p.Snapshot.Files)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range generated {
		snapshot.Files[name] = data
	}
	const orphan = ".claude/rules/retired.md"
	snapshot.Files[orphan] = []byte("<!-- Generated by Markitect -->\n# Retired policy\n")
	p, err = Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	findings := CheckOutputs(p)
	if len(findings) != 1 || findings[0].Code != "stale-output" || findings[0].Path != orphan {
		t.Fatalf("orphaned aggregate adapter was not rejected: %#v", findings)
	}
	if Generated([]byte("Example:\n<!-- Generated by Markitect -->\n")) {
		t.Fatal("a quoted marker outside the first content must not grant ownership")
	}
}
