package app

import (
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/render"
)

func TestCheckOutputsDoesNotTreatGeneratedSchemaYAMLAsOwnedOutput(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := render.Generate(p.Graph)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range generated {
		snapshot.Files[name] = append([]byte(nil), data...)
		snapshot.Modes[name] = "100644"
	}

	const schemaPath = "schema/Text.yaml"
	snapshot.Files[schemaPath] = []byte("# Generated by Markitect; schema resource\ntype: object\n")
	snapshot.Modes[schemaPath] = "100644"
	if !Generated(snapshot.Files[schemaPath]) {
		t.Fatal("test setup: schema fixture is not marked as generated")
	}

	p, err = Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	if findings := CheckOutputs(p); len(findings) != 0 {
		t.Fatalf("generated schema YAML was treated as a Markitect-owned or stale output: %#v", findings)
	}
}
