package app

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Glacius-Labs/Markitect/internal/core"
	"github.com/Glacius-Labs/Markitect/internal/render"
	"github.com/Glacius-Labs/Markitect/internal/source"
)

func Generated(data []byte) bool {
	// The marker must be the first content, optionally after provider metadata.
	// Quoted examples elsewhere in a source file never grant output ownership.
	text := strings.TrimSpace(string(data))
	if strings.HasPrefix(text, "---\n") || strings.HasPrefix(text, "---\r\n") {
		lines := strings.Split(text, "\n")
		closed := false
		for i := 1; i < len(lines); i++ {
			if strings.TrimSpace(lines[i]) == "---" {
				text = strings.TrimSpace(strings.Join(lines[i+1:], "\n"))
				closed = true
				break
			}
		}
		if !closed {
			return false
		}
	}
	return strings.HasPrefix(text, "<!-- Generated by Markitect;") || strings.HasPrefix(text, "# Generated by Markitect;")
}

func CheckOutputs(p *Project) []core.Diagnostic {
	if len(p.Diagnostics) > 0 {
		return nil
	}
	outputs, err := render.Generate(p.Graph)
	if err != nil {
		return []core.Diagnostic{{Code: "render", Message: err.Error()}}
	}
	var findings []core.Diagnostic
	names := sortedFiles(outputs)
	for _, name := range names {
		data, ok := p.Snapshot.Files[name]
		if !ok {
			findings = append(findings, core.Diagnostic{Code: "missing-output", Path: name, Message: "generated file is missing; run markitect render --write"})
		} else if !bytes.Equal(normalize(data), normalize(outputs[name])) {
			findings = append(findings, core.Diagnostic{Code: "output-drift", Path: name, Message: "generated file differs from its canonical source"})
		}
	}
	for _, name := range sortedFiles(p.Snapshot.Files) {
		if (strings.HasSuffix(name, ".md") || strings.HasSuffix(name, ".toml")) && Generated(p.Snapshot.Files[name]) {
			if _, ok := outputs[name]; !ok {
				findings = append(findings, core.Diagnostic{Code: "stale-output", Path: name, Message: "previously generated file has no current source; inspect and remove in the same migration"})
			}
		}
	}
	return findings
}

func normalize(data []byte) []byte { return bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n")) }

func safeDestination(root, name string) (string, error) {
	if name == "" || strings.Contains(name, "\\") || strings.Contains(name, ":") || filepath.IsAbs(name) {
		return "", fmt.Errorf("unsafe output path %q", name)
	}
	for _, part := range strings.Split(name, "/") {
		if part == "" || part == "." || part == ".." || strings.EqualFold(part, ".git") {
			return "", fmt.Errorf("unsafe output path %q", name)
		}
	}
	absolute, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	// Check the root and each existing ancestor for symbolic links/reparse aliases.
	resolved, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", err
	}
	if !strings.EqualFold(filepath.Clean(resolved), filepath.Clean(absolute)) {
		return "", fmt.Errorf("output root contains a symlink: %s", root)
	}
	current := absolute
	for _, part := range strings.Split(name, "/") {
		current = filepath.Join(current, part)
		info, err := os.Lstat(current)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return "", err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("symlink in output path %s", name)
		}
		resolved, err := filepath.EvalSymlinks(current)
		if err != nil {
			return "", err
		}
		if !strings.EqualFold(filepath.Clean(resolved), filepath.Clean(current)) {
			return "", fmt.Errorf("reparse point in output path %s", name)
		}
	}
	return current, nil
}

func WriteOutputs(root string, p *Project) ([]string, error) {
	if !p.Snapshot.Provisional {
		return nil, fmt.Errorf("writing a snapshot is forbidden; render the isolated working tree")
	}
	if len(p.Diagnostics) > 0 {
		return nil, fmt.Errorf("cannot render while project diagnostics remain")
	}
	rootAbs, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	branch := ""
	if p.Graph.Project.Spec.Profile != "generic" {
		branch, err = writeBranchName(rootAbs)
		if err != nil {
			return nil, err
		}
	} else if current, branchErr := source.GitOutput(rootAbs, "branch", "--show-current"); branchErr == nil {
		branch = strings.TrimSpace(string(current))
		if branch == "" || strings.EqualFold(branch, "master") || strings.EqualFold(branch, "main") {
			return nil, fmt.Errorf("render --write requires a non-protected branch")
		}
	}
	lockDir := filepath.Join(rootAbs, ".artifacts", "markitect")
	if _, err = safeDestination(rootAbs, ".artifacts/markitect/write.lock"); err != nil {
		return nil, err
	}
	if err = os.MkdirAll(lockDir, 0755); err != nil {
		return nil, err
	}
	lock, err := os.OpenFile(filepath.Join(lockDir, "write.lock"), os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return nil, fmt.Errorf("another renderer owns write.lock (inspect an abandoned lock before removing it): %w", err)
	}
	lock.Close()
	defer os.Remove(filepath.Join(lockDir, "write.lock"))
	if branch != "" {
		if err := ensureWriteBranch(rootAbs, branch); err != nil {
			return nil, err
		}
	}
	outputs, err := render.Generate(p.Graph)
	if err != nil {
		return nil, err
	}
	names := sortedFiles(outputs)
	fresh, err := source.Load(root, "")
	if err != nil {
		return nil, err
	}
	if fresh.Digest() != p.Snapshot.Digest() {
		return nil, fmt.Errorf("source inventory changed since capture; reload before rendering")
	}
	// Validate the entire plan and reject concurrent edits before writing anything.
	for _, name := range names {
		if branch != "" {
			if err := ensureWriteBranch(rootAbs, branch); err != nil {
				return nil, err
			}
		}
		dest, err := safeDestination(root, name)
		if err != nil {
			return nil, err
		}
		data, err := os.ReadFile(dest)
		original, existed := p.Snapshot.Files[name]
		if err == nil {
			if !existed || !bytes.Equal(data, original) {
				return nil, fmt.Errorf("output changed since source capture: %s", name)
			}
			if !Generated(data) && !bytes.Equal(normalize(data), normalize(outputs[name])) {
				return nil, fmt.Errorf("refusing to replace an unmanaged file: %s", name)
			}
		} else if !os.IsNotExist(err) {
			return nil, err
		} else if existed {
			return nil, fmt.Errorf("output removed since source capture: %s", name)
		}
	}
	// Recheck all YAML source bytes, including configuration, before output writes.
	for _, r := range p.Resources {
		dest, err := safeDestination(root, r.Path)
		if err != nil {
			return nil, err
		}
		current, err := os.ReadFile(dest)
		if err != nil || !bytes.Equal(current, p.Snapshot.Files[r.Path]) {
			return nil, fmt.Errorf("source changed since capture: %s", r.Path)
		}
	}
	var written []string
	for _, name := range names {
		if branch != "" {
			if err := ensureWriteBranch(rootAbs, branch); err != nil {
				return written, err
			}
		}
		dest, err := safeDestination(root, name)
		if err != nil {
			return written, err
		}
		if err = os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
			return written, err
		}
		// The author must hold a single-writer worktree. Revalidation reduces accidental
		// races; a filesystem cannot provide a multi-file transaction here.
		if _, err = safeDestination(root, name); err != nil {
			return written, err
		}
		current, readErr := os.ReadFile(dest)
		original, existed := p.Snapshot.Files[name]
		if existed && (readErr != nil || !bytes.Equal(current, original)) {
			return written, fmt.Errorf("output changed during render: %s", name)
		}
		if !existed && !os.IsNotExist(readErr) {
			return written, fmt.Errorf("output appeared during render: %s", name)
		}
		if branch != "" {
			if err := ensureWriteBranch(rootAbs, branch); err != nil {
				return written, err
			}
		}
		if err = atomicWrite(dest, outputs[name]); err != nil {
			return written, err
		}
		written = append(written, name)
	}
	sort.Strings(written)
	final, err := source.Load(root, "")
	if err != nil {
		return written, err
	}
	// Our own output changes are expected. Any other concurrent edit means this
	// batch is not a valid rendered candidate and must be checked again.
	for _, name := range names {
		delete(final.Files, name)
		delete(fresh.Files, name)
	}
	if final.Digest() != fresh.Digest() {
		return written, fmt.Errorf("source changed during rendering; outputs are provisional, rerun check")
	}
	if branch != "" {
		if err := ensureWriteBranch(rootAbs, branch); err != nil {
			return written, err
		}
	}
	return written, nil
}

func writableBranch(root string) error {
	_, err := writeBranchName(root)
	return err
}

// writeBranchName returns the named, non-protected Git branch for a write.
func writeBranchName(root string) (string, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	branch, err := source.GitOutput(absolute, "branch", "--show-current")
	if err != nil {
		return "", fmt.Errorf("writing canonical sources requires an isolated Git branch: %w", err)
	}
	name := strings.TrimSpace(string(branch))
	if name == "" || strings.EqualFold(name, "master") || strings.EqualFold(name, "main") {
		return "", fmt.Errorf("writing requires an isolated non-protected Git branch")
	}
	return name, nil
}

// ensureWriteBranch catches a branch switch, including one to a different
// branch at the same HEAD, during a multi-file write.
func ensureWriteBranch(root, expected string) error {
	current, err := writeBranchName(root)
	if err != nil {
		return fmt.Errorf("write branch changed or became protected: %w", err)
	}
	if current != expected {
		return fmt.Errorf("branch changed during write from %q to %q", expected, current)
	}
	return nil
}

func atomicWrite(dest string, data []byte) error {
	f, err := os.CreateTemp(filepath.Dir(dest), ".markitect-*")
	if err != nil {
		return err
	}
	temporary := f.Name()
	defer os.Remove(temporary)
	if _, err = f.Write(data); err != nil {
		f.Close()
		return err
	}
	if err = f.Sync(); err != nil {
		f.Close()
		return err
	}
	if err = f.Close(); err != nil {
		return err
	}
	if err = os.Chmod(temporary, 0644); err != nil {
		return err
	}
	return os.Rename(temporary, dest)
}

func lockWriter(root string) (func(), error) {
	lockPath, err := safeDestination(root, ".artifacts/markitect/write.lock")
	if err != nil {
		return nil, err
	}
	if err = os.MkdirAll(filepath.Dir(lockPath), 0755); err != nil {
		return nil, err
	}
	lock, err := os.OpenFile(lockPath, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return nil, fmt.Errorf("renderer lock is already present: %w", err)
	}
	lock.Close()
	return func() { os.Remove(lockPath) }, nil
}

// WriteSchemas only owns its generated schema files; path validation also
// protects standalone tool checkouts that do not yet have Git metadata.
func WriteSchemas(root string, outputs map[string][]byte) error {
	branch := ""
	var unlock func()
	if _, err := os.Lstat(filepath.Join(root, ".git")); err == nil {
		branch, err = writeBranchName(root)
		if err != nil {
			return err
		}
		unlock, err = lockWriter(root)
		if err != nil {
			return err
		}
		defer unlock()
		if err := ensureWriteBranch(root, branch); err != nil {
			return err
		}
	}
	for _, name := range sortedFiles(outputs) {
		if !strings.HasPrefix(name, "schema/") {
			return fmt.Errorf("invalid schema target %s", name)
		}
		dest, err := safeDestination(root, name)
		if err != nil {
			return err
		}
		old, err := os.ReadFile(dest)
		if err == nil && !Generated(old) {
			return fmt.Errorf("unmanaged schema output %s", name)
		}
		if err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	for _, name := range sortedFiles(outputs) {
		if branch != "" {
			if err := ensureWriteBranch(root, branch); err != nil {
				return err
			}
		}
		dest, err := safeDestination(root, name)
		if err != nil {
			return err
		}
		if err = os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
			return err
		}
		if branch != "" {
			if err := ensureWriteBranch(root, branch); err != nil {
				return err
			}
		}
		if err = atomicWrite(dest, outputs[name]); err != nil {
			return err
		}
	}
	if branch != "" {
		if err := ensureWriteBranch(root, branch); err != nil {
			return err
		}
	}
	return nil
}
