package app

import (
	"strings"
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/core"
	"github.com/Glacius-Labs/Markitect/internal/format"
	"github.com/Glacius-Labs/Markitect/internal/render"
	"github.com/Glacius-Labs/Markitect/internal/snapshot"
)

const nestedStaleOutput = "<!-- Generated by Markitect; source: removed.yaml -->\nold generated content\n"

func TestCheckOutputsScopesStaleInventoryToIndependentNestedProject(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	outputs, err := render.Generate(p.Graph, snapshot.Files)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range outputs {
		snapshot.Files[name] = append([]byte(nil), data...)
		snapshot.Modes[name] = "100644"
	}
	addNestedProject(t, snapshot, "examples/minimal/markitect.yaml")
	snapshot.Files["examples/minimal/docs/markitect/old.md"] = []byte(nestedStaleOutput)
	snapshot.Modes["examples/minimal/docs/markitect/old.md"] = "100644"

	p, err = Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	if len(p.Diagnostics) != 0 {
		t.Fatalf("independent nested Project altered parent parsing: %#v", p.Diagnostics)
	}
	if p.Graph.Project.Path != projectPath {
		t.Fatalf("root model Project = %q, want %q", p.Graph.Project.Path, projectPath)
	}
	for _, resource := range p.Resources {
		if strings.HasPrefix(resource.Path, "examples/minimal/") {
			t.Fatalf("nested Project resource entered the parent model: %#v", resource)
		}
	}
	for _, finding := range CheckOutputs(p) {
		if finding.Code == "stale-output" && finding.Path == "examples/minimal/docs/markitect/old.md" {
			t.Fatalf("child-owned stale output was attributed to parent: %#v", finding)
		}
	}
	if roots := independentNestedProjectRoots(p, outputs); len(roots) != 1 || roots[0] != "examples/minimal" {
		t.Fatalf("independent nested Project roots = %v, want [examples/minimal]", roots)
	}
}

func TestCheckOutputsKeepsParentOutputChecksWithNestedProject(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	outputs, err := render.Generate(p.Graph, snapshot.Files)
	if err != nil {
		t.Fatal(err)
	}
	outputNames := sortedFiles(outputs)
	if len(outputNames) < 2 {
		t.Fatalf("fixture produced only %d output(s), need drift and missing cases", len(outputNames))
	}
	for name, data := range outputs {
		snapshot.Files[name] = append([]byte(nil), data...)
		snapshot.Modes[name] = "100644"
	}
	addNestedProject(t, snapshot, "examples/minimal/markitect.yaml")

	driftPath, missingPath := outputNames[0], outputNames[1]
	snapshot.Files[driftPath] = append(snapshot.Files[driftPath], []byte("changed\n")...)
	delete(snapshot.Files, missingPath)
	delete(snapshot.Modes, missingPath)
	p, err = Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	findings := CheckOutputs(p)
	if !hasFindingPath(findings, "output-drift", driftPath) {
		t.Fatalf("nested Project hid parent output drift at %s: %#v", driftPath, findings)
	}
	if !hasFindingPath(findings, "missing-output", missingPath) {
		t.Fatalf("nested Project hid missing parent output at %s: %#v", missingPath, findings)
	}
}

func TestCheckOutputsStillReportsUnscopedStaleMarker(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	snapshot.Files["notes/old.md"] = []byte(nestedStaleOutput)
	snapshot.Modes["notes/old.md"] = "100644"
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	if !hasFindingPath(CheckOutputs(p), "stale-output", "notes/old.md") {
		t.Fatal("ordinary stale marker outside a nested Project was not reported")
	}
}

func TestInvalidNestedManifestsDoNotHideStaleMarkers(t *testing.T) {
	cases := map[string][]byte{
		"malformed-yaml":  []byte("kind: [Project\n"),
		"domain-envelope": []byte("apiVersion: markitect.example.org/v1alpha1\nkind: Domain\nmetadata: {name: nested}\nspec: {}\n"),
		"closed-project":  []byte("apiVersion: markitect.example.org/v1alpha1\nkind: Project\nmetadata: {name: nested}\nspec: {unknown: true}\n"),
	}
	for name, manifest := range cases {
		t.Run(name, func(t *testing.T) {
			snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
			manifestPath := "examples/" + name + "/markitect.yaml"
			stalePath := "examples/" + name + "/docs/old.md"
			snapshot.Files[manifestPath] = manifest
			snapshot.Modes[manifestPath] = "100644"
			snapshot.Files[stalePath] = []byte(nestedStaleOutput)
			snapshot.Modes[stalePath] = "100644"
			p, err := Parse(snapshot)
			if err != nil {
				t.Fatal(err)
			}
			if !hasFindingPath(CheckOutputs(p), "stale-output", stalePath) {
				t.Fatalf("invalid nested manifest hid stale output %s", stalePath)
			}
		})
	}
}

func TestNestedProjectCannotHideParentAreasOrOutputs(t *testing.T) {
	t.Run("area overlap", func(t *testing.T) {
		snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
		addNestedProject(t, snapshot, "docs/general/nested/markitect.yaml")
		snapshot.Files["docs/general/nested/old.md"] = []byte(nestedStaleOutput)
		snapshot.Modes["docs/general/nested/old.md"] = "100644"
		p, err := Parse(snapshot)
		if err != nil {
			t.Fatal(err)
		}
		if !hasFindingCode(p.Diagnostics, "project.count") {
			t.Fatalf("nested Project inside parent Area did not remain a structural error: %#v", p.Diagnostics)
		}
		if roots := independentNestedProjectRoots(p, map[string][]byte{}); len(roots) != 0 {
			t.Fatalf("nested Project overlapping parent Area was accepted as a boundary: %v", roots)
		}
	})

	t.Run("expected output overlap", func(t *testing.T) {
		snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
		p, err := Parse(snapshot)
		if err != nil {
			t.Fatal(err)
		}
		outputs, err := render.Generate(p.Graph, snapshot.Files)
		if err != nil {
			t.Fatal(err)
		}
		for name, data := range outputs {
			snapshot.Files[name] = append([]byte(nil), data...)
			snapshot.Modes[name] = "100644"
		}
		addNestedProject(t, snapshot, "docs/markitect/markitect.yaml")
		stalePath := "docs/markitect/old.md"
		snapshot.Files[stalePath] = []byte(nestedStaleOutput)
		snapshot.Modes[stalePath] = "100644"
		p, err = Parse(snapshot)
		if err != nil {
			t.Fatal(err)
		}
		if !hasFindingPath(CheckOutputs(p), "stale-output", stalePath) {
			t.Fatalf("nested Project overlapping parent output namespace hid %s", stalePath)
		}
	})
}

func addNestedProject(t *testing.T, snap *snapshot.Snapshot, manifestPath string) {
	t.Helper()
	root := strings.TrimSuffix(manifestPath, "/markitect.yaml")
	manifest := core.Resource{
		APIVersion: core.APIVersion,
		Kind:       "Project",
		Metadata:   core.Metadata{Name: "nested-project"},
		Spec:       core.Spec{Areas: []core.Area{{Name: "nested", Path: root + "/docs"}}},
	}
	data, err := format.Encode(manifest)
	if err != nil {
		t.Fatal(err)
	}
	snap.Files[manifestPath] = data
	snap.Modes[manifestPath] = "100644"
}

func hasFindingPath(findings []core.Diagnostic, code, path string) bool {
	for _, finding := range findings {
		if finding.Code == code && finding.Path == path {
			return true
		}
	}
	return false
}

func hasFindingCode(findings []core.Diagnostic, code string) bool {
	for _, finding := range findings {
		if finding.Code == code {
			return true
		}
	}
	return false
}
