package app

import (
	"strings"
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/render"
)

func TestProjectionStaleInventoryMatchesCheckAndPreservesOwnership(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	outputs, err := render.Generate(p.Graph, snapshot.Files)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range outputs {
		snapshot.Files[name] = append([]byte(nil), data...)
		snapshot.Modes[name] = "100644"
	}
	addNestedProject(t, snapshot, "examples/minimal/markitect.yaml")
	snapshot.Files["examples/minimal/docs/old.md"] = []byte(nestedStaleOutput)
	snapshot.Modes["examples/minimal/docs/old.md"] = "100644"
	snapshot.Files["examples/minimal/.agents/old.toml"] = []byte("# Generated by Markitect; source: old-agent.yaml\nold\n")
	snapshot.Modes["examples/minimal/.agents/old.toml"] = "100644"
	snapshot.Files["benchmark/previous.md"] = []byte(nestedStaleOutput)
	snapshot.Modes["benchmark/previous.md"] = "100644"
	snapshot.Files["benchmark/previous.toml"] = []byte("# Generated by Markitect; source: old-agent.yaml\nold\n")
	snapshot.Modes["benchmark/previous.toml"] = "100644"
	snapshot.Files["schema/Project.yaml"] = []byte("# Generated by Markitect; edit Go validation declarations.\n")
	snapshot.Modes["schema/Project.yaml"] = "100644"

	p, err = Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	observation, err := ObserveProjection(p, "test-version", "test-tool")
	if err != nil {
		t.Fatal(err)
	}
	wantStale := []string{"benchmark/previous.md", "benchmark/previous.toml"}
	if strings.Join(observation.Stale, "\n") != strings.Join(wantStale, "\n") {
		t.Fatalf("projection stale paths = %v, want %v", observation.Stale, wantStale)
	}
	findings := CheckOutputs(p)
	var checkedStale []string
	for _, finding := range findings {
		if finding.Code == "stale-output" {
			checkedStale = append(checkedStale, finding.Path)
		}
	}
	if strings.Join(checkedStale, "\n") != strings.Join(observation.Stale, "\n") {
		t.Fatalf("check stale paths %v differ from reconcile observation %v", checkedStale, observation.Stale)
	}
	plan, err := PlanProjection(p, "test-version", "test-tool")
	if err != nil {
		t.Fatal(err)
	}
	if plan.Status != "incomplete" || strings.Join(plan.Stale, "\n") != strings.Join(wantStale, "\n") {
		t.Fatalf("projection plan status/stale = %q/%v, want incomplete/%v", plan.Status, plan.Stale, wantStale)
	}
	for _, operation := range plan.Operations {
		if operation.Action == "delete" {
			t.Fatalf("projection plan introduced a delete operation: %#v", operation)
		}
		if operation.Path == "examples/minimal/docs/old.md" || operation.Path == "benchmark/previous.md" || operation.Path == "benchmark/previous.toml" {
			t.Fatalf("plan targets stale inventory instead of current renderer outputs: %#v", operation)
		}
	}
}

func TestProjectionStaleInventoryRejectsMalformedNestedProject(t *testing.T) {
	snapshot := fixtureFiles(t, "fixture", "Keep the owner source.", projectNS)
	manifestPath := "examples/malformed/markitect.yaml"
	stalePath := "examples/malformed/docs/old.md"
	snapshot.Files[manifestPath] = []byte("apiVersion: markitect.example.org/v1alpha1\nkind: Project\nmetadata: {name: child}\nspec: {unknown: true}\n")
	snapshot.Modes[manifestPath] = "100644"
	snapshot.Files[stalePath] = []byte(nestedStaleOutput)
	snapshot.Modes[stalePath] = "100644"
	p, err := Parse(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	observation, err := ObserveProjection(p, "test-version", "test-tool")
	if err != nil {
		t.Fatal(err)
	}
	if !hasPath(observation.Stale, stalePath) {
		t.Fatalf("malformed nested manifest hid stale output %s: %#v", stalePath, observation.Stale)
	}
}

func hasPath(paths []string, want string) bool {
	for _, path := range paths {
		if path == want {
			return true
		}
	}
	return false
}
