package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/Glacius-Labs/Markitect/internal/core"
	"github.com/Glacius-Labs/Markitect/internal/format"
	"github.com/Glacius-Labs/Markitect/internal/host"
	"github.com/Glacius-Labs/Markitect/internal/host/embedded"
)

func runAuthoring(o commandOptions, errout io.Writer, emit func(any) int, fail func(error) int) int {
	if o.flagCount != 0 {
		fmt.Fprintln(errout, "authoring accepts no flags; its compiled context has no repository or revision")
		return 2
	}
	digest, err := currentToolDigest()
	if err != nil {
		return fail(err)
	}
	ctx, err := embedded.Context(version, digest)
	if err != nil {
		return fail(err)
	}
	return emit(ctx)
}

func runSchema(o commandOptions, errout io.Writer, emit func(any) int, fail func(error) int) int {
	registry := core.NewRegistry()
	if _, statErr := os.Stat(filepath.Join(o.root, "markitect.yaml")); statErr == nil {
		project, loadErr := host.Load(o.root, "")
		if loadErr != nil {
			return fail(loadErr)
		}
		if project.Graph != nil && project.Graph.Registry != nil {
			registry = project.Graph.Registry
		}
	} else if !os.IsNotExist(statErr) {
		return fail(statErr)
	}
	schemas, err := format.SchemasWithRegistry(registry)
	if err != nil {
		return fail(err)
	}
	for name, data := range schemas {
		target := filepath.Join(o.root, filepath.FromSlash(name))
		data = append([]byte("# Generated by Markitect; edit Go validation declarations.\n"), data...)
		schemas[name] = data
		if !o.write {
			existing, err := os.ReadFile(target)
			if err != nil || string(existing) != string(data) {
				fmt.Fprintln(errout, "schema drift:", name)
				return 1
			}
		}
	}
	if o.write {
		if err = host.WriteSchemas(o.root, schemas); err != nil {
			return fail(err)
		}
	}
	return emit(map[string]any{"status": "passed", "schemas": len(schemas), "version": version})
}
