apiVersion: commerce.example.org/v1
kind: UseCase
metadata:
  namespace: commerce
  name: create-order
purpose: Allows a customer to create an order.
spec:
  handledBy:
    apiVersion: commerce.example.org/v1
    kind: Handler
    namespace: commerce
    name: create-order-handler
