package render

import (
	"strings"
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/core"
)

func proseGraph(text string) (*core.Graph, map[string][]byte) {
	area := core.Area{Name: "general", Path: "docs/general"}
	p := resource("Project", "markitect.yaml", "prose", "", core.Spec{Targets: []string{"markdown"}, Areas: []core.Area{area}})
	skill := resource("Skill", "docs/general/skills/setup.yaml", "setup", "general", core.Spec{Text: text, Description: "Read [tools](../tools/README.md)."})
	workflow := resource("Workflow", "docs/general/workflows/setup.yaml", "setup", "general", core.Spec{Text: "## Steps\n\nSet up."})
	g := &core.Graph{Project: p, Resources: map[string]*core.Resource{skill.GraphKey(): skill, workflow.GraphKey(): workflow}, ResourceAreas: map[string]core.Area{skill.GraphKey(): area, workflow.GraphKey(): area}}
	files := map[string][]byte{skill.Path: []byte("canonical Skill"), workflow.Path: []byte("canonical Workflow"), "docs/general/tools/README.md": []byte("# Tools"), "docs/general/images/guide #1.png": []byte("opaque image")}
	return g, files
}

func TestProseNavigationRebasesCanonicalOrdinaryAndImageTargets(t *testing.T) {
	g, files := proseGraph("[Workflow](../workflows/setup.yaml#steps) [old view](../workflows/setup.md?mode=read#steps)\n![guide](<../images/guide%20%231.png>)\n[tools][tool]\n\n[tool]: ../tools/README.md?mode=read#help \"Tools title\"\n\n`[literal](../tools/README.md)`\n\n```md\n[literal](../tools/README.md)\n```\n")
	outputs, err := Generate(g, files)
	if err != nil {
		t.Fatal(err)
	}
	body := string(outputs["docs/markitect/general/skills/setup.skill.md"])
	for _, want := range []string{
		"[Workflow](../workflows/setup.workflow.md#steps)",
		"[old view](../workflows/setup.workflow.md?mode=read#steps)",
		"![guide](<../../../general/images/guide%20%231.png>)",
		"[tool]: ../../../general/tools/README.md?mode=read#help \"Tools title\"",
		"**Description:** Read [tools](../../../general/tools/README.md).",
		"`[literal](../tools/README.md)`",
		"```md\n[literal](../tools/README.md)\n```",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("missing %q in:\n%s", want, body)
		}
	}
	if len(g.Edges) != 0 || len(g.Relationships) != 0 {
		t.Fatal("prose created graph relationships")
	}
}

func TestProseNavigationOrdinaryCompanionAliasTakesPrecedence(t *testing.T) {
	for _, tc := range []struct {
		name string
		data []byte
		want string
	}{
		{"ordinary", []byte("# Human-owned workflow"), "../../../general/workflows/setup.md#steps"},
		{"old generated", []byte("<!-- Generated by Markitect; source: docs/general/workflows/setup.yaml -->\n"), "../workflows/setup.workflow.md#steps"},
		{"absent", nil, "../workflows/setup.workflow.md#steps"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			g, files := proseGraph("[Workflow](../workflows/setup.md#steps)")
			if tc.data != nil {
				files["docs/general/workflows/setup.md"] = tc.data
			}
			outputs, err := Generate(g, files)
			if err != nil {
				t.Fatal(err)
			}
			if body := string(outputs["docs/markitect/general/skills/setup.skill.md"]); !strings.Contains(body, "[Workflow]("+tc.want+")") {
				t.Fatalf("wrong alias resolution: %s", body)
			}
		})
	}
}

func TestProseNavigationRejectsOnlyUsedAmbiguousAliases(t *testing.T) {
	g, files := proseGraph("No prose links.")
	second := resource("Rule", "docs/general/workflows/setup.yml", "setup", "general", core.Spec{Text: "Rule."})
	g.Resources[second.GraphKey()] = second
	g.ResourceAreas[second.GraphKey()] = core.Area{Name: "general", Path: "docs/general"}
	if _, err := Generate(g, files); err != nil {
		t.Fatal("unused companion alias blocked outputs:", err)
	}
	g.Resources["general/Skill/setup"].Spec.Text = "[ambiguous](../workflows/setup.md)"
	if _, err := Generate(g, files); err == nil || !strings.Contains(err.Error(), "ambiguous companion alias") {
		t.Fatalf("ambiguous alias: %v", err)
	}
	files["docs/general/workflows/setup.md"] = []byte("# Ordinary file")
	if _, err := Generate(g, files); err != nil {
		t.Fatal("ordinary file did not disambiguate:", err)
	}
}

func TestProseNavigationDoesNotProjectPackagePaths(t *testing.T) {
	g, files := proseGraph("[archive-looking input](../archive/item.yaml)")
	imported := resource("Workflow", "docs/general/archive/item.yaml", "imported", "general", core.Spec{})
	imported.Package = "guidance"
	g.Resources[imported.GraphKey()] = imported
	files[imported.Path] = []byte("opaque local artifact")
	outputs, err := Generate(g, files)
	if err != nil {
		t.Fatal(err)
	}
	if body := string(outputs["docs/markitect/general/skills/setup.skill.md"]); !strings.Contains(body, "../../../general/archive/item.yaml") {
		t.Fatalf("package path projected locally: %s", body)
	}
	if outputs["docs/markitect/general/archive/item.workflow.md"] != nil {
		t.Fatal("imported view invented")
	}
}

func TestProviderInlineProseRebasesToCanonicalInputs(t *testing.T) {
	for _, targets := range [][]string{{"codex", "claude"}, {"markdown", "codex", "claude"}} {
		g, files := proseGraph("Unused Skill prose.")
		g.Project.Spec.Targets = targets
		g.Project.Spec.ProviderAdapters = &core.ProviderAdapters{InlineAgentText: true}
		agent := resource("Agent", "docs/general/agents/helper.yaml", "helper", "general", core.Spec{Text: "[Workflow](../workflows/setup.yaml#steps) [legacy](../workflows/setup.md) [tools](../tools/README.md)"})
		g.Resources[agent.GraphKey()] = agent
		g.ResourceAreas[agent.GraphKey()] = core.Area{Name: "general", Path: "docs/general"}
		files[agent.Path] = []byte("canonical Agent")
		outputs, err := Generate(g, files)
		if err != nil {
			t.Fatal(err)
		}
		for _, output := range []string{".claude/agents/helper.md", ".codex/agents/helper.toml"} {
			body := string(outputs[output])
			for _, want := range []string{"../../docs/general/workflows/setup.yaml#steps", "../../docs/general/workflows/setup.yaml)", "../../docs/general/tools/README.md"} {
				if !strings.Contains(body, want) {
					t.Errorf("%s missing %q: %s", output, want, body)
				}
			}
		}
		if len(targets) == 2 {
			for p := range outputs {
				if strings.HasPrefix(p, "docs/markitect/") {
					t.Fatal("disabled Markdown produced output")
				}
			}
		}
	}
}

func TestProseNavigationPreservesExternalURLsAndLocalAnchors(t *testing.T) {
	text := "[https](https://example.invalid/a#b) [host](//example.invalid/a) [site](/docs/a) [anchor](#steps) [query](?mode=read)"
	g, files := proseGraph(text)
	outputs, err := Generate(g, files)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(outputs["docs/markitect/general/skills/setup.skill.md"]), text) {
		t.Fatal("external or local destination changed")
	}
	g.Resources["general/Skill/setup"].Spec.Text = "[escape](../../../../secret.md)"
	if _, err := Generate(g, files); err == nil || !strings.Contains(err.Error(), "escapes the repository") {
		t.Fatalf("repository escape: %v", err)
	}
}

func TestProseNavigationRejectsWindowsDrivePaths(t *testing.T) {
	for _, destination := range []string{"C:/guide.md", `C:\guide.md`} {
		g, files := proseGraph("[guide](" + destination + ")")
		if _, err := Generate(g, files); err == nil || !strings.Contains(err.Error(), "not a portable relative path") {
			t.Fatalf("drive destination %q: %v", destination, err)
		}
	}
	text := "[mail](mailto:guide@example.invalid) [custom](custom:guide.md)"
	g, files := proseGraph(text)
	outputs, err := Generate(g, files)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(outputs["docs/markitect/general/skills/setup.skill.md"]), text) {
		t.Fatal("non-file URL scheme changed")
	}
}

func TestProseNavigationUnusedReferenceDoesNotResolveAmbiguousAlias(t *testing.T) {
	g, files := proseGraph("[unused]: ../workflows/setup.md\n\nNo link.\n")
	second := resource("Rule", "docs/general/workflows/setup.yml", "setup", "general", core.Spec{Text: "Rule."})
	g.Resources[second.GraphKey()] = second
	g.ResourceAreas[second.GraphKey()] = core.Area{Name: "general", Path: "docs/general"}
	if _, err := Generate(g, files); err != nil {
		t.Fatal("unused reference blocked outputs:", err)
	}
	g.Resources["general/Skill/setup"].Spec.Text = "[unused]: ../workflows/setup.md\n\n[unused]\n"
	if _, err := Generate(g, files); err == nil || !strings.Contains(err.Error(), "ambiguous companion alias") {
		t.Fatalf("used ambiguous reference: %v", err)
	}
}

func TestProseNavigationErrorOrderIsDeterministic(t *testing.T) {
	g, files := proseGraph("[escape](../../../../secret.md)")
	g.Resources["general/Workflow/setup"].Spec.Text = "[escape](../../../../secret.md)"
	for range 30 {
		if _, err := Generate(g, files); err == nil || !strings.Contains(err.Error(), "resource general/Skill/setup prose navigation:") {
			t.Fatalf("unexpected first diagnostic: %v", err)
		}
	}
}

func TestProseNavigationSharesReferencesAcrossDescriptionAndText(t *testing.T) {
	g, files := proseGraph("[guide]: ../tools/README.md#help\n")
	g.Resources["general/Skill/setup"].Spec.Description = "Read [guide]."
	outputs, err := Generate(g, files)
	if err != nil {
		t.Fatal(err)
	}
	body := string(outputs["docs/markitect/general/skills/setup.skill.md"])
	if !strings.Contains(body, "**Description:** Read [guide].") || !strings.Contains(body, "[guide]: ../../../general/tools/README.md#help") {
		t.Fatalf("description reference was not projected from the complete prose: %s", body)
	}
}
