// Package render translates validated Markitect resources into readable views
// and provider entrypoints. It performs no filesystem writes.
package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Glacius-Labs/Markitect/internal/core"
)

// Marker is embedded in every generated file so ownership remains visible.
const Marker = "Generated by Markitect"

// Generate returns deterministic generated files keyed by repository-relative
// POSIX paths. The caller owns safe filesystem writes.
func Generate(g *core.Graph) (map[string][]byte, error) {
	outputs, _, err := GenerateWithOwners(g)
	return outputs, err
}

// GenerateWithOwners returns generated files and the resource keys that
// explicitly own each file. Provider outputs are associated only with their
// source resource or configured RuleAdapter references.
func GenerateWithOwners(g *core.Graph) (map[string][]byte, map[string][]string, error) {
	if g == nil {
		return nil, nil, fmt.Errorf("graph is nil")
	}
	resources := make([]*core.Resource, 0, len(g.Resources))
	for _, r := range g.Resources {
		if r == nil {
			return nil, nil, fmt.Errorf("graph contains a nil resource")
		}
		if r.Package != "" {
			continue
		}
		resources = append(resources, r)
	}
	sort.Slice(resources, func(i, j int) bool {
		if resources[i].Path != resources[j].Path {
			return resources[i].Path < resources[j].Path
		}
		return resources[i].GraphKey() < resources[j].GraphKey()
	})

	outputs := map[string][]byte{}
	ownerSets := map[string]map[string]bool{}
	canonical := map[string]*core.Resource{}
	for _, r := range resources {
		if err := validRepoPath(r.Path); err != nil {
			return nil, nil, fmt.Errorf("resource %s source path: %w", r.Key(), err)
		}
		folded := foldPath(r.Path)
		if prior := canonical[folded]; prior != nil {
			return nil, nil, fmt.Errorf("source path collision: %q and %q", prior.Path, r.Path)
		}
		canonical[folded] = r
		if r.Kind == "Project" {
			continue
		}
		view := companionPath(r.Path)
		content, err := renderCompanion(r, view, g)
		if err != nil {
			return nil, nil, err
		}
		if err := addOwned(outputs, ownerSets, view, content, r.Key()); err != nil {
			return nil, nil, err
		}
	}

	targets := map[string]bool{}
	if g.Project != nil {
		for _, target := range g.Project.Spec.Targets {
			target = strings.ToLower(target)
			if target != "codex" && target != "claude" {
				return nil, nil, fmt.Errorf("unsupported provider target %q", target)
			}
			targets[target] = true
		}
	}
	if targets["codex"] || targets["claude"] {
		for _, r := range resources {
			if r.Kind == "Project" {
				continue
			}
			switch r.Kind {
			case "Skill":
				if targets["codex"] {
					p := ".agents/skills/" + r.Metadata.Name + "/SKILL.md"
					if err := addOwned(outputs, ownerSets, p, renderSkill(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
				if targets["claude"] {
					p := ".claude/skills/" + r.Metadata.Name + "/SKILL.md"
					if err := addOwned(outputs, ownerSets, p, renderSkill(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
			case "Agent":
				if targets["codex"] {
					p := ".codex/agents/" + r.Metadata.Name + ".toml"
					if err := addOwned(outputs, ownerSets, p, renderCodexAgent(r, p), r.Key()); err != nil {
						return nil, nil, err
					}
				}
				if targets["claude"] {
					p := ".claude/agents/" + r.Metadata.Name + ".md"
					if err := addOwned(outputs, ownerSets, p, renderClaudeAgent(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
			}
		}
	}
	if targets["claude"] {
		ruleOutputs, ruleOwners, err := renderRules(g)
		if err != nil {
			return nil, nil, err
		}
		for p, b := range ruleOutputs {
			if err := add(outputs, p, b); err != nil {
				return nil, nil, err
			}
			ownerSets[p] = map[string]bool{}
			for _, key := range ruleOwners[p] {
				ownerSets[p][key] = true
			}
		}
	}
	outputs, err := checkCollisions(outputs, canonical)
	if err != nil {
		return nil, nil, err
	}
	owners := make(map[string][]string, len(ownerSets))
	for output, set := range ownerSets {
		for key := range set {
			owners[output] = append(owners[output], key)
		}
		sort.Strings(owners[output])
	}
	return outputs, owners, nil
}

func addOwned(outputs map[string][]byte, owners map[string]map[string]bool, name string, data []byte, resource string) error {
	if err := add(outputs, name, data); err != nil {
		return err
	}
	if owners[name] == nil {
		owners[name] = map[string]bool{}
	}
	owners[name][resource] = true
	return nil
}
