// Package render translates validated Markitect resources into readable views
// and provider entrypoints. It performs no filesystem writes.
package render

import (
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/Glacius-Labs/Markitect/internal/core"
)

// Marker is embedded in every generated file so ownership remains visible.
const Marker = "Generated by Markitect"

// Generate returns deterministic generated files keyed by repository-relative
// POSIX paths. The caller owns safe filesystem writes.
func Generate(g *core.Graph) (map[string][]byte, error) {
	outputs, _, err := GenerateWithOwners(g)
	return outputs, err
}

// GenerateWithOwners returns generated files and the resource keys that
// explicitly own each file. Provider outputs are associated only with their
// source resource or configured RuleAdapter references.
func GenerateWithOwners(g *core.Graph) (map[string][]byte, map[string][]string, error) {
	if g == nil {
		return nil, nil, fmt.Errorf("graph is nil")
	}
	resources := make([]*core.Resource, 0, len(g.Resources))
	for _, r := range g.Resources {
		if r == nil {
			return nil, nil, fmt.Errorf("graph contains a nil resource")
		}
		if r.Package != "" {
			continue
		}
		resources = append(resources, r)
	}
	sort.Slice(resources, func(i, j int) bool {
		if resources[i].Path != resources[j].Path {
			return resources[i].Path < resources[j].Path
		}
		return resources[i].GraphKey() < resources[j].GraphKey()
	})

	outputs := map[string][]byte{}
	ownerSets := map[string]map[string]bool{}
	canonical := map[string]*core.Resource{}
	for _, r := range resources {
		if err := validRepoPath(r.Path); err != nil {
			return nil, nil, fmt.Errorf("resource %s source path: %w", r.Key(), err)
		}
		folded := foldPath(r.Path)
		if prior := canonical[folded]; prior != nil {
			return nil, nil, fmt.Errorf("source path collision: %q and %q", prior.Path, r.Path)
		}
		canonical[folded] = r
		if r.Kind == "Project" {
			continue
		}
		view := companionPath(r.Path)
		content, err := renderCompanion(r, view, g)
		if err != nil {
			return nil, nil, err
		}
		if err := addOwned(outputs, ownerSets, view, content, r.Key()); err != nil {
			return nil, nil, err
		}
	}

	targets := map[string]bool{}
	if g.Project != nil {
		for _, target := range g.Project.Spec.Targets {
			target = strings.ToLower(target)
			if target != "codex" && target != "claude" {
				return nil, nil, fmt.Errorf("unsupported provider target %q", target)
			}
			targets[target] = true
		}
	}
	if targets["codex"] || targets["claude"] {
		for _, r := range resources {
			if r.Kind == "Project" {
				continue
			}
			switch r.Kind {
			case "Skill":
				if targets["codex"] {
					p := ".agents/skills/" + r.Metadata.Name + "/SKILL.md"
					if err := addOwned(outputs, ownerSets, p, renderSkill(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
				if targets["claude"] {
					p := ".claude/skills/" + r.Metadata.Name + "/SKILL.md"
					if err := addOwned(outputs, ownerSets, p, renderSkill(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
			case "Agent":
				if targets["codex"] {
					p := ".codex/agents/" + r.Metadata.Name + ".toml"
					if err := addOwned(outputs, ownerSets, p, renderCodexAgent(r, p), r.Key()); err != nil {
						return nil, nil, err
					}
				}
				if targets["claude"] {
					p := ".claude/agents/" + r.Metadata.Name + ".md"
					if err := addOwned(outputs, ownerSets, p, renderClaudeAgent(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
			}
		}
	}
	if targets["claude"] {
		ruleOutputs, ruleOwners, err := renderRules(g)
		if err != nil {
			return nil, nil, err
		}
		for p, b := range ruleOutputs {
			if err := add(outputs, p, b); err != nil {
				return nil, nil, err
			}
			ownerSets[p] = map[string]bool{}
			for _, key := range ruleOwners[p] {
				ownerSets[p][key] = true
			}
		}
	}
	outputs, err := checkCollisions(outputs, canonical)
	if err != nil {
		return nil, nil, err
	}
	owners := make(map[string][]string, len(ownerSets))
	for output, set := range ownerSets {
		for key := range set {
			owners[output] = append(owners[output], key)
		}
		sort.Strings(owners[output])
	}
	return outputs, owners, nil
}

func addOwned(outputs map[string][]byte, owners map[string]map[string]bool, name string, data []byte, resource string) error {
	if err := add(outputs, name, data); err != nil {
		return err
	}
	if owners[name] == nil {
		owners[name] = map[string]bool{}
	}
	owners[name][resource] = true
	return nil
}

func renderCompanion(r *core.Resource, target string, g *core.Graph) ([]byte, error) {
	var b strings.Builder
	b.WriteString("<!-- " + Marker + "; source: " + r.Path + " -->\n")
	b.WriteString("# " + r.Kind + ": " + r.Metadata.Name + "\n\n")
	if r.Spec.Description != "" {
		b.WriteString("**Description:** " + r.Spec.Description + "\n\n")
	}
	if r.Spec.Text != "" {
		b.WriteString(r.Spec.Text)
		if !strings.HasSuffix(r.Spec.Text, "\n") {
			b.WriteByte('\n')
		}
	}
	links := dependencyLinks(r, target, g)
	if len(links) > 0 {
		b.WriteString("\n## Dependencies\n\n")
		for _, link := range links {
			writeDependency(&b, link)
		}
	}
	return []byte(b.String()), nil
}

type dependencyLink struct{ label, path, instruction string }

func dependencyLinks(r *core.Resource, from string, g *core.Graph) []dependencyLink {
	type typedRef struct {
		ref  core.Ref
		kind string
	}
	refs := make([]typedRef, 0, len(r.Spec.Rules)+len(r.Spec.Uses)+len(r.Spec.Needs)+len(r.Spec.Implements))
	for _, ref := range r.Spec.Rules {
		refs = append(refs, typedRef{ref, "Rule"})
	}
	for _, ref := range r.Spec.Uses {
		refs = append(refs, typedRef{ref, ""})
	}
	for _, ref := range r.Spec.Needs {
		refs = append(refs, typedRef{ref, "Contract"})
	}
	for _, ref := range r.Spec.Implements {
		refs = append(refs, typedRef{ref, "Contract"})
	}
	seen := map[string]bool{}
	links := make([]dependencyLink, 0, len(refs))
	for _, item := range refs {
		ref := item.ref
		key := ref.GraphKey(r.Package, r.Metadata.Namespace, item.kind)
		if seen[key] {
			continue
		}
		seen[key] = true
		dep := findResource(g, ref, r.Package, r.Metadata.Namespace, item.kind)
		if dep == nil || dep.Kind == "Project" || dep.Path == "" {
			continue
		}
		if dep.Package != "" {
			version := ""
			if g.Project != nil {
				for _, pin := range g.Project.Spec.Packages {
					if pin.Name == dep.Package {
						version = pin.Version
						break
					}
				}
			}
			label := "Package dependency: " + dep.GraphKey()
			if version != "" {
				label += " (version " + version + ")"
			}
			instruction := "Select this exported dependency with `markitect context --repo . --package " + dep.Package + " --namespace " + dep.Metadata.Namespace + " --kind " + dep.Kind + " --name " + dep.Metadata.Name + "`."
			links = append(links, dependencyLink{label: label, instruction: instruction})
			continue
		}
		companion := companionPath(dep.Path)
		links = append(links, dependencyLink{label: dep.Kind + ": " + dep.Metadata.Name, path: relative(from, companion)})
	}
	sort.Slice(links, func(i, j int) bool { return links[i].label < links[j].label })
	return links
}

func renderSkill(r *core.Resource, target string, g *core.Graph) []byte {
	var b strings.Builder
	b.WriteString("---\nname: " + yamlQuote(r.Metadata.Name) + "\ndescription: " + yamlQuote(r.Spec.Description) + "\n---\n\n")
	b.WriteString("<!-- " + Marker + "; source: " + relative(target, r.Path) + " -->\n\n")
	b.WriteString("Read the [canonical skill definition](" + relative(target, companionPath(r.Path)) + ") before acting.\n")
	links := dependencyLinks(r, target, g)
	if len(links) > 0 {
		b.WriteString("\n## Dependencies\n\n")
		for _, link := range links {
			writeDependency(&b, link)
		}
	}
	return []byte(b.String())
}

func renderCodexAgent(r *core.Resource, target string) []byte {
	p := r.Spec.Providers.Codex
	var b strings.Builder
	b.WriteString("# " + Marker + "; source: " + relative(target, r.Path) + "\n")
	if p != nil {
		writeTOMLString(&b, "name", r.Metadata.Name)
		writeTOMLString(&b, "description", r.Spec.Description)
		if p.Model != "" {
			writeTOMLString(&b, "model", p.Model)
		}
		if p.Effort != "" {
			writeTOMLString(&b, "model_reasoning_effort", p.Effort)
		}
		if p.Sandbox != "" {
			writeTOMLString(&b, "sandbox_mode", p.Sandbox)
		}
	}
	writeTOMLString(&b, "developer_instructions", "Read the canonical [agent view]("+relative(target, companionPath(r.Path))+") and follow its stated scope.")
	return []byte(b.String())
}

func renderClaudeAgent(r *core.Resource, target string, g *core.Graph) []byte {
	p := r.Spec.Providers.Claude
	var b strings.Builder
	b.WriteString("---\nname: " + yamlQuote(r.Metadata.Name) + "\ndescription: " + yamlQuote(r.Spec.Description) + "\n")
	if p != nil {
		if p.Model != "" {
			b.WriteString("model: " + yamlQuote(p.Model) + "\n")
		}
		if p.Effort != "" {
			b.WriteString("effort: " + yamlQuote(p.Effort) + "\n")
		}
		if p.PermissionMode != "" {
			b.WriteString("permissionMode: " + yamlQuote(p.PermissionMode) + "\n")
		}
		if len(p.Tools) > 0 {
			b.WriteString("tools: " + yamlArray(p.Tools) + "\n")
		}
		if len(p.DisallowedTools) > 0 {
			b.WriteString("disallowedTools: " + yamlArray(p.DisallowedTools) + "\n")
		}
		if p.MaxTurns > 0 {
			fmt.Fprintf(&b, "maxTurns: %d\n", p.MaxTurns)
		}
	}
	b.WriteString("---\n\n<!-- " + Marker + "; source: " + relative(target, r.Path) + " -->\n\n")
	b.WriteString("Read the [canonical agent view](" + relative(target, companionPath(r.Path)) + ") before acting.\n")
	links := dependencyLinks(r, target, g)
	if len(links) > 0 {
		b.WriteString("\n## Dependencies\n\n")
		for _, link := range links {
			writeDependency(&b, link)
		}
	}
	return []byte(b.String())
}

func renderRules(g *core.Graph) (map[string][]byte, map[string][]string, error) {
	out := map[string][]byte{}
	owners := map[string][]string{}
	if g.Project == nil || g.Project.Spec.RuleAdapters == nil {
		return out, owners, nil
	}
	names := make([]string, 0, len(g.Project.Spec.RuleAdapters))
	for name := range g.Project.Spec.RuleAdapters {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		refs := g.Project.Spec.RuleAdapters[name]
		var b strings.Builder
		b.WriteString("<!-- " + Marker + " -->\n# " + title(name) + "\n\n")
		for _, ref := range refs {
			if ref.Package != "" {
				return nil, nil, fmt.Errorf("external ruleAdapters are not supported: %q", ref.GraphKey("", "", "Rule"))
			}
			r := findResource(g, ref, "", "", "Rule")
			if r == nil {
				return nil, nil, fmt.Errorf("rule adapter %q references unresolved rule %q", name, ref.Name)
			}
			p := ".claude/rules/" + name + ".md"
			b.WriteString("- [" + r.Metadata.Name + "](" + relative(p, companionPath(r.Path)) + ")\n")
			owners[p] = append(owners[p], r.Key())
		}
		out[".claude/rules/"+name+".md"] = []byte(b.String())
	}
	for output := range owners {
		sort.Strings(owners[output])
	}
	return out, owners, nil
}

func writeDependency(b *strings.Builder, link dependencyLink) {
	if link.instruction != "" {
		b.WriteString("- " + link.label + ". " + link.instruction + "\n")
		return
	}
	b.WriteString("- [" + link.label + "](" + link.path + ")\n")
}

func findResource(g *core.Graph, ref core.Ref, defaultPackage, namespace, kind string) *core.Resource {
	if ref.Kind != "" {
		kind = ref.Kind
	}
	if ref.Namespace != "" {
		namespace = ref.Namespace
	}
	return g.Resources[ref.GraphKey(defaultPackage, namespace, kind)]
}

func companionPath(source string) string {
	ext := path.Ext(source)
	if ext == "" {
		return source + ".md"
	}
	return strings.TrimSuffix(source, ext) + ".md"
}

func relative(fromFile, toFile string) string {
	return relativePath(path.Dir(fromFile), toFile)
}

func relativePath(fromDir, to string) string {
	// Implement POSIX relative paths without consulting the host OS.
	from := strings.Split(strings.Trim(fromDir, "/"), "/")
	toParts := strings.Split(strings.Trim(to, "/"), "/")
	if len(from) == 1 && from[0] == "" {
		from = nil
	}
	i := 0
	for i < len(from) && i < len(toParts) && from[i] == toParts[i] {
		i++
	}
	parts := make([]string, 0, len(from)-i+len(toParts)-i)
	for range from[i:] {
		parts = append(parts, "..")
	}
	parts = append(parts, toParts[i:]...)
	if len(parts) == 0 {
		return "."
	}
	return strings.Join(parts, "/")
}

func add(outputs map[string][]byte, name string, data []byte) error {
	if err := validRepoPath(name); err != nil {
		return fmt.Errorf("invalid output path %q: %w", name, err)
	}
	if _, exists := outputs[name]; exists {
		return fmt.Errorf("duplicate generated output %q", name)
	}
	outputs[name] = data
	return nil
}

func checkCollisions(outputs map[string][]byte, sources map[string]*core.Resource) (map[string][]byte, error) {
	seen := map[string]string{}
	for source := range sources {
		seen[foldPath(source)] = "source " + source
	}
	paths := make([]string, 0, len(outputs))
	for p := range outputs {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		key := foldPath(p)
		if prior, ok := seen[key]; ok {
			return nil, fmt.Errorf("output path collision: %s conflicts with %q", prior, p)
		}
		seen[key] = "output " + p
	}
	return outputs, nil
}

func validRepoPath(p string) error {
	if p == "" || strings.ContainsAny(p, "\\:\x00") || strings.HasPrefix(p, "/") || path.Clean(p) != p || p == "." || strings.HasPrefix(p, "../") {
		return fmt.Errorf("path must be repository-relative and normalized")
	}
	for _, part := range strings.Split(p, "/") {
		if part == "" || part == "." || part == ".." {
			return fmt.Errorf("path contains unsafe component")
		}
	}
	return nil
}

func foldPath(p string) string  { return strings.ToLower(p) }
func yamlQuote(s string) string { return strconv.Quote(s) }
func yamlArray(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = yamlQuote(v)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
func writeTOMLString(b *strings.Builder, key, value string) {
	fmt.Fprintf(b, "%s = %s\n", key, strconv.Quote(value))
}
func writeTOMLArray(b *strings.Builder, key string, values []string) {
	fmt.Fprintf(b, "%s = %s\n", key, yamlArray(values))
}
func title(s string) string { return strings.ReplaceAll(s, "-", " ") }
