// Package render translates validated Markitect resources into readable views
// and provider entrypoints. It performs no filesystem writes.
package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Glacius-Labs/Markitect/internal/core"
)

// Marker is embedded in every generated file so ownership remains visible.
const Marker = "Generated by Markitect"

// Generate returns deterministic generated files keyed by repository-relative
// POSIX paths. files is the explicit local snapshot used to resolve prose navigation;
// package archive paths stay separate. The caller owns safe filesystem writes.
func Generate(g *core.Graph, files map[string][]byte) (map[string][]byte, error) {
	outputs, _, err := GenerateWithOwners(g, files)
	return outputs, err
}

// GenerateWithOwners returns generated files and the resource keys that
// explicitly own each file. Provider outputs are associated only with their
// source resource or configured RuleAdapter references.
func GenerateWithOwners(g *core.Graph, files map[string][]byte) (map[string][]byte, map[string][]string, error) {
	if g == nil {
		return nil, nil, fmt.Errorf("graph is nil")
	}
	resources := make([]*core.Resource, 0, len(g.Resources))
	for _, r := range g.Resources {
		if r == nil {
			return nil, nil, fmt.Errorf("graph contains a nil resource")
		}
		if r.Package != "" {
			continue
		}
		resources = append(resources, r)
	}
	sort.Slice(resources, func(i, j int) bool {
		if resources[i].Path != resources[j].Path {
			return resources[i].Path < resources[j].Path
		}
		return resources[i].GraphKey() < resources[j].GraphKey()
	})

	outputs := map[string][]byte{}
	ownerSets := map[string]map[string]bool{}
	canonical := map[string]*core.Resource{}
	for _, r := range resources {
		if err := validRepoPath(r.Path); err != nil {
			return nil, nil, fmt.Errorf("resource %s source path: %w", r.Key(), err)
		}
		folded := foldPath(r.Path)
		if prior := canonical[folded]; prior != nil {
			return nil, nil, fmt.Errorf("source path collision: %q and %q", prior.Path, r.Path)
		}
		canonical[folded] = r
		if r.Kind == "Project" {
			continue
		}
	}

	targets := map[string]bool{}
	var adapters *core.ProviderAdapters
	if g.Project != nil {
		adapters = g.Project.Spec.ProviderAdapters
		for _, target := range g.Project.Spec.Targets {
			target = strings.ToLower(target)
			if target != "codex" && target != "claude" && target != "markdown" {
				return nil, nil, fmt.Errorf("unsupported provider target %q", target)
			}
			targets[target] = true
		}
	}
	navigation := newProseNavigation(g, resources, files)
	if targets["markdown"] {
		viewPaths, err := MarkdownViewPaths(g)
		if err != nil {
			return nil, nil, err
		}
		domainPaths, err := DomainMarkdownPaths(g)
		if err != nil {
			return nil, nil, err
		}
		views := make([]string, 0, len(viewPaths))
		for view := range viewPaths {
			views = append(views, view)
		}
		sort.Strings(views)
		for _, view := range views {
			resource := viewPaths[view]
			content, err := renderCompanion(resource, view, g, navigation)
			if err != nil {
				return nil, nil, err
			}
			if err := addOwned(outputs, ownerSets, view, content, resource.GraphKey()); err != nil {
				return nil, nil, err
			}
		}
		domains := make([]string, 0, len(domainPaths))
		for view := range domainPaths {
			domains = append(domains, view)
		}
		sort.Strings(domains)
		for _, view := range domains {
			domain := domainPaths[view]
			content, err := renderDomainContract(domain, view, g)
			if err != nil {
				return nil, nil, err
			}
			owner := "domain:" + domain.APIVersion + "/" + domain.Name
			if err := addOwned(outputs, ownerSets, view, content, owner); err != nil {
				return nil, nil, err
			}
		}
		if len(viewPaths) > 0 || len(domainPaths) > 0 {
			if err := addMarkdownNavigation(outputs, ownerSets, viewPaths, domainPaths, g.Project.Key()); err != nil {
				return nil, nil, err
			}
		}
	}
	if targets["codex"] || targets["claude"] {
		for _, r := range resources {
			if r.Kind == "Project" {
				continue
			}
			if r.APIVersion != "" && r.APIVersion != core.APIVersion {
				continue
			}
			switch r.Kind {
			case "Skill":
				if targets["codex"] {
					p := ".agents/skills/" + r.Metadata.Name + "/SKILL.md"
					if err := addOwned(outputs, ownerSets, p, renderSkill(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
				if targets["claude"] {
					p := ".claude/skills/" + r.Metadata.Name + "/SKILL.md"
					if err := addOwned(outputs, ownerSets, p, renderSkill(r, p, g), r.Key()); err != nil {
						return nil, nil, err
					}
				}
			case "Agent":
				if targets["codex"] {
					p := ".codex/agents/" + r.Metadata.Name + ".toml"
					content, err := renderCodexAgent(r, p, adapters, navigation)
					if err != nil {
						return nil, nil, err
					}
					if err := addOwned(outputs, ownerSets, p, content, r.Key()); err != nil {
						return nil, nil, err
					}
				}
				if targets["claude"] {
					p := ".claude/agents/" + r.Metadata.Name + ".md"
					content, err := renderClaudeAgent(r, p, g, adapters, navigation)
					if err != nil {
						return nil, nil, err
					}
					if err := addOwned(outputs, ownerSets, p, content, r.Key()); err != nil {
						return nil, nil, err
					}
				}
			}
		}
	}
	if targets["claude"] {
		ruleOutputs, ruleOwners, err := renderRules(g)
		if err != nil {
			return nil, nil, err
		}
		for p, b := range ruleOutputs {
			if err := add(outputs, p, b); err != nil {
				return nil, nil, err
			}
			ownerSets[p] = map[string]bool{}
			for _, key := range ruleOwners[p] {
				ownerSets[p][key] = true
			}
		}
	}
	if err := renderConfiguredAdapters(g, targets, adapters, outputs, ownerSets); err != nil {
		return nil, nil, err
	}
	outputs, err := checkCollisions(outputs, canonical)
	if err != nil {
		return nil, nil, err
	}
	owners := make(map[string][]string, len(ownerSets))
	for output, set := range ownerSets {
		for key := range set {
			owners[output] = append(owners[output], key)
		}
		sort.Strings(owners[output])
	}
	return outputs, owners, nil
}

func addOwned(outputs map[string][]byte, owners map[string]map[string]bool, name string, data []byte, resource string) error {
	if err := add(outputs, name, data); err != nil {
		return err
	}
	if owners[name] == nil {
		owners[name] = map[string]bool{}
	}
	owners[name][resource] = true
	return nil
}
