apiVersion: architecture.markitect.org/v1alpha1
kind: Feature
metadata:
    name: availability
    namespace: engineering
spec:
    module:
        kind: Module
        name: inventory
        namespace: engineering
    summary: Query and reserve available stock.
