from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = (ROOT / "README.md").read_text(encoding="utf-8")

# Paths below this prefix are generated by `markitect docs --write`.
GENERATED = "docs/markitect/"


class ReadmeTests(unittest.TestCase):
    def test_named_fixture_paths_exist(self) -> None:
        named = sorted(set(re.findall(r"`((?:\.markitect|src|tests|docs)/[^`\s]*)`", README)))
        self.assertTrue(named, "the guide names no fixture paths")
        for path in named:
            if path.startswith(GENERATED):
                continue
            with self.subTest(path=path):
                self.assertTrue((ROOT / path).exists(), f"the guide names {path}, which the fixture lacks")

    def test_guide_covers_every_shop_slice(self) -> None:
        guide = README.lower()
        for package in sorted(path.name for path in (ROOT / "src" / "shop").iterdir() if path.is_dir() and not path.name.startswith("_")):
            with self.subTest(package=package):
                self.assertIn(package, guide)

    def test_guide_does_not_imply_a_provider_run(self) -> None:
        self.assertIn("without a provider runner or credentials", README)
        self.assertIn("no agent starts automatically", README)


if __name__ == "__main__":
    unittest.main()
