package host

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/infrastructure/source"
	"github.com/Glacius-Labs/Markitect/internal/modules/artifactcoverage"
	"github.com/Glacius-Labs/Markitect/internal/render"
)

func TestCheckArtifactsUsesParsedOwnershipAndFindsNewFiles(t *testing.T) {
	root := artifactCoverageFixture(t)
	report, err := CheckArtifacts(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if report.Status != "passed" {
		t.Fatalf("initial coverage failed: %#v", report.Findings)
	}
	for _, expected := range [][2]string{{"docs/general/rule.yaml", "canonical"}, {"docs/general/reference.md", "input"}, {"tools/check.go", "tooling"}, {"docs/general/retained.md", "excluded"}} {
		if !artifactHasClass(report, expected[0], expected[1]) {
			t.Errorf("missing %s classification for %s: %#v", expected[1], expected[0], report.Files)
		}
	}
	if !artifactHasClass(report, "docs/markitect/general/skill.skill.md", "generated") {
		t.Fatalf("renderer ownership missing: %#v", report.Files)
	}
	if err := os.Chmod(filepath.Join(root, "tools/check.go"), 0755); err != nil {
		t.Fatal(err)
	}
	report, err = CheckArtifacts(root, "meta/coverage.yaml")
	if err != nil || report.Status != "passed" {
		t.Fatalf("executable tooling file should remain explicitly owned: err=%v findings=%#v", err, report.Findings)
	}
	writeArtifactFixture(t, root, "docs/general/new-untracked.md", "untracked managed file\n")
	report, err = CheckArtifacts(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if report.Status != "failed" || !artifactHasFinding(report, "unmanaged", "docs/general/new-untracked.md") {
		t.Fatalf("working-tree addition was not rejected: %#v", report.Findings)
	}
}

func TestCheckArtifactsReportsRenamedInputsAndRendererOwnershipFailures(t *testing.T) {
	root := artifactCoverageFixture(t)
	if err := os.Rename(filepath.Join(root, "docs/general/reference.md"), filepath.Join(root, "docs/general/renamed-reference.md")); err != nil {
		t.Fatal(err)
	}
	writeArtifactFixture(t, root, "docs/markitect/general/orphan.md", "<!-- Generated by Markitect; source: deleted.yaml -->\n")
	writeArtifactFixture(t, root, "docs/markitect/general/schema.yaml", "# Generated by Markitect; external schema generator.\n")
	config := strings.Replace(string(mustReadArtifactFile(t, root, "meta/coverage.yaml")),
		"    - path: tools/check.go\n      owner: artifact coverage checker\n",
		"    - path: tools/check.go\n      owner: artifact coverage checker\n    - path: docs/markitect/general/schema.yaml\n      owner: schema generator\n", 1)
	writeArtifactFixture(t, root, "meta/coverage.yaml", config)
	if err := os.Remove(filepath.Join(root, "docs/markitect/general/skill.skill.md")); err != nil {
		t.Fatal(err)
	}
	report, err := CheckArtifacts(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range [][2]string{{"unmanaged", "docs/general/renamed-reference.md"}, {"missing-generated", "docs/markitect/general/skill.skill.md"}, {"orphan-generated", "docs/markitect/general/orphan.md"}} {
		if !artifactHasFinding(report, expected[0], expected[1]) {
			t.Errorf("missing %s for %s: %#v", expected[0], expected[1], report.Findings)
		}
	}
	if !artifactHasFindingMessage(report, "input.missing", "docs/general/rule.yaml", "docs/general/reference.md") {
		t.Errorf("deleted declared input did not retain its source diagnostic: %#v", report.Findings)
	}
	if !artifactHasClass(report, "docs/markitect/general/schema.yaml", "tooling") {
		t.Fatalf("explicit non-renderer generator owner was lost: %#v", report.Files)
	}
	if !strings.Contains(artifactFindingMessage(report, "missing-generated", "docs/markitect/general/skill.skill.md"), "run markitect render --write") {
		t.Fatalf("legacy remediation text was not preserved: %#v", report.Findings)
	}
}

func TestCheckArtifactsRejectsCollisionsAndSymlinks(t *testing.T) {
	root := artifactCoverageFixture(t)
	config := string(mustReadArtifactFile(t, root, "meta/coverage.yaml"))
	config = strings.Replace(config,
		"    - path: tools/check.go\n      owner: artifact coverage checker\n",
		"    - path: docs/general/rule.yaml\n      owner: accidental canonical overlap\n    - path: tools/check.go\n      owner: artifact coverage checker\n", 1)
	writeArtifactFixture(t, root, "meta/coverage.yaml", config)
	report, err := CheckArtifacts(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !artifactHasFinding(report, "ownership-collision", "docs/general/rule.yaml") {
		t.Fatalf("canonical/tooling collision was not rejected: %#v", report.Findings)
	}
	if err := os.Remove(filepath.Join(root, "meta/coverage.yaml")); err != nil {
		t.Fatal(err)
	}
	generatedCollision := strings.Replace(artifactCoverageConfig(),
		"    - path: tools/check.go\n      owner: artifact coverage checker\n",
		"    - path: docs/markitect/general/skill.skill.md\n      owner: accidental output owner\n    - path: tools/check.go\n      owner: artifact coverage checker\n", 1)
	writeArtifactFixture(t, root, "meta/coverage.yaml", generatedCollision)
	report, err = CheckArtifacts(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !artifactHasFinding(report, "ownership-collision", "docs/markitect/general/skill.skill.md") {
		t.Fatalf("renderer/tooling collision was not rejected: %#v", report.Findings)
	}
	if err := os.Remove(filepath.Join(root, "meta/coverage.yaml")); err != nil {
		t.Fatal(err)
	}
	writeArtifactFixture(t, root, "meta/coverage.yaml", artifactCoverageConfig())
	if err := os.Symlink(filepath.Join(root, "docs/general/reference.md"), filepath.Join(root, "docs/general/link.md")); err != nil {
		t.Skipf("symlink creation is unavailable: %v", err)
	}
	if _, err := CheckArtifacts(root, "meta/coverage.yaml"); err == nil || !strings.Contains(err.Error(), "symlink or reparse point") {
		t.Fatalf("managed symlink was not rejected: %v", err)
	}
}

func TestCheckArtifactsHandlesEmptyExistingRootsAndStaleDeclarations(t *testing.T) {
	root := t.TempDir()
	writeArtifactFixture(t, root, "markitect.yaml", "apiVersion: markitect.example.org/v1alpha1\nkind: Project\nmetadata:\n  name: sample\nspec: {}\n")
	if err := os.MkdirAll(filepath.Join(root, "empty-managed"), 0755); err != nil {
		t.Fatal(err)
	}
	writeArtifactFixture(t, root, "tools/existing.txt", "helper\n")
	writeArtifactFixture(t, root, "meta/coverage.yaml", `apiVersion: markitect.example.org/artifact-coverage/v1alpha1
kind: ArtifactCoverage
spec:
  roots: [empty-managed, meta, tools]
  tooling:
    - path: meta/coverage.yaml
      owner: coverage policy
    - path: tools/existing.txt
      owner: helper
  exclusions:
    - path: tools/removed.txt
      reason: obsolete helper removed in migration
`)
	if err := os.Remove(filepath.Join(root, "tools/existing.txt")); err != nil {
		t.Fatal(err)
	}
	report, err := CheckArtifacts(root, "meta/coverage.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if artifactHasFinding(report, "stale-root", "empty-managed") {
		t.Fatalf("existing directory was treated as stale: %#v", report.Findings)
	}
	if !artifactHasFinding(report, "stale-tooling", "tools/existing.txt") || !artifactHasFinding(report, "stale-exclusion", "tools/removed.txt") {
		t.Fatalf("stale declarations were not reported: %#v", report.Findings)
	}
}

func artifactCoverageFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeArtifactFixture(t, root, "markitect.yaml", `apiVersion: markitect.example.org/v1alpha1
kind: Project
metadata:
  name: sample
spec:
  targets: [markdown]
  areas:
    - name: general
      path: docs/general
`)
	writeArtifactFixture(t, root, "docs/general/rule.yaml", `apiVersion: markitect.example.org/v1alpha1
kind: Rule
metadata:
  name: policy
  namespace: general
spec:
  text: Keep policy explicit.
  files: [docs/general/reference.md]
`)
	writeArtifactFixture(t, root, "docs/general/skill.yaml", `apiVersion: markitect.example.org/v1alpha1
kind: Skill
metadata:
  name: entry
  namespace: general
spec:
  text: Follow the policy.
  rules:
    - name: policy
`)
	writeArtifactFixture(t, root, "docs/general/reference.md", "A declared opaque project input.\n")
	writeArtifactFixture(t, root, "docs/general/retained.md", "Reasoned exclusion.\n")
	writeArtifactFixture(t, root, "tools/check.go", "package tools\n")
	writeArtifactFixture(t, root, "meta/coverage.yaml", artifactCoverageConfig())
	snap, err := source.Load(root, "")
	if err != nil {
		t.Fatal(err)
	}
	project, err := Parse(snap)
	if err != nil {
		t.Fatal(err)
	}
	outputs, _, err := render.GenerateWithOwners(project.Graph, snap.Files)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range outputs {
		writeArtifactFixture(t, root, name, string(data))
	}
	return root
}

func artifactCoverageConfig() string {
	return `apiVersion: markitect.example.org/artifact-coverage/v1alpha1
kind: ArtifactCoverage
spec:
  roots: [docs/general, docs/markitect, meta, tools]
  tooling:
    - path: meta/coverage.yaml
      owner: artifact coverage policy
    - path: tools/check.go
      owner: artifact coverage checker
  exclusions:
    - path: docs/general/retained.md
      reason: retained historical example awaiting migration
`
}

func writeArtifactFixture(t *testing.T, root, name, contents string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(contents), 0644); err != nil {
		t.Fatal(err)
	}
}

func mustReadArtifactFile(t *testing.T, root, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func artifactHasClass(report artifactcoverage.Report, name, class string) bool {
	for _, file := range report.Files {
		if file.Path == name && file.Class == class {
			return true
		}
	}
	return false
}

func artifactHasFinding(report artifactcoverage.Report, code, name string) bool {
	for _, finding := range report.Findings {
		if finding.Code == code && finding.Path == name {
			return true
		}
	}
	return false
}

func artifactFindingMessage(report artifactcoverage.Report, code, name string) string {
	for _, finding := range report.Findings {
		if finding.Code == code && finding.Path == name {
			return finding.Message
		}
	}
	return ""
}

func artifactHasFindingMessage(report artifactcoverage.Report, code, name, message string) bool {
	return strings.Contains(artifactFindingMessage(report, code, name), message)
}
