package host

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/host/canonical"
	"github.com/Glacius-Labs/Markitect/internal/host/records"
	"github.com/Glacius-Labs/Markitect/internal/infrastructure/source"
)

func TestScopedPlannerExcludesOnlyOwnerSelectedBytes(t *testing.T) {
	root, revision, _ := scopedCanonicalFixture(t)
	excludedPath := "docs/represented/unowned.bin"
	if err := os.MkdirAll(filepath.Dir(filepath.Join(root, filepath.FromSlash(excludedPath))), 0755); err != nil {
		t.Fatal(err)
	}
	// Inventory can stat this file, but any selected byte acquisition would
	// exceed the source reader's per-file bound and fail the proposal.
	largeFile := filepath.Join(root, filepath.FromSlash(excludedPath))
	file, err := os.Create(largeFile)
	if err != nil {
		t.Fatal(err)
	}
	if err := file.Close(); err != nil {
		t.Fatal(err)
	}
	if err := os.Truncate(largeFile, source.DefaultMaxFileBytes+1); err != nil {
		t.Fatal(err)
	}
	missingPath := "docs/represented/deleted.bin"
	exclusion := []CanonicalTargetExclusion{
		{Path: excludedPath, Reason: "generated by an external system"},
		{Path: missingPath, Reason: "not part of the selected artifact scope"},
	}
	plan, err := proposeScopedCanonicalReconciliation(root, revision, revision, "examples/canonical-projection/canonical.yaml", nil, false, exclusion, nil)
	if err != nil {
		t.Fatal(err)
	}
	if plan.Status != "planned" || len(plan.UnknownArtifacts) != 0 {
		t.Fatalf("explicit exclusion did not bound unknown inventory: status=%s unknown=%v", plan.Status, plan.UnknownArtifacts)
	}
	if len(plan.ExplicitExcludedArtifacts) != 2 {
		t.Fatalf("excluded metadata missing: %+v", plan.ExplicitExcludedArtifacts)
	}
	excluded := plan.ExplicitExcludedArtifacts[0]
	if excluded.Path != excludedPath || excluded.Reason != exclusion[0].Reason || excluded.State != "present" || excluded.Metadata == nil || excluded.Metadata.Size != source.DefaultMaxFileBytes+1 {
		t.Fatalf("excluded metadata was not fully classified: %+v", excluded)
	}
	missing := plan.ExplicitExcludedArtifacts[1]
	if missing.Path != missingPath || missing.State != "missing" || missing.Metadata != nil || plan.Status == "passed" {
		t.Fatalf("missing exclusion implied complete or passing evidence: %+v status=%s", missing, plan.Status)
	}
	if _, found := plan.observed.Files[excludedPath]; found {
		t.Fatal("excluded content entered the acquired snapshot")
	}
	for _, name := range plan.ObservedPaths {
		if name == excludedPath {
			t.Fatal("excluded path was requested from working-file acquisition")
		}
	}
	for _, proposal := range plan.Proposals {
		if _, found := proposal.Request.TargetFiles[excludedPath]; found {
			t.Fatal("excluded bytes entered Module target files")
		}
	}
	changedReason := []CanonicalTargetExclusion{
		{Path: excludedPath, Reason: "owner-reviewed external output"},
		{Path: missingPath, Reason: "not part of the selected artifact scope"},
	}
	changed, err := proposeScopedCanonicalReconciliation(root, revision, revision, "examples/canonical-projection/canonical.yaml", nil, false, changedReason, nil)
	if err != nil || changed.Digest == plan.Digest {
		t.Fatalf("plan digest did not bind exclusion reason: err=%v", err)
	}
}

func TestTargetExclusionRefusesProtectedAndAliasedPaths(t *testing.T) {
	requestIDs := []string{"core/v1:Projection:docs"}
	requests := map[string]canonical.ProjectionRequest{
		requestIDs[0]: {TargetPrefix: "docs/represented"},
	}
	prior := map[string]records.ProjectionRecord{
		"core/v1:Projection:docs": {Artifacts: []records.Artifact{{Path: "docs/represented/owned.md"}}},
	}
	cases := []struct {
		name       string
		exclusion  CanonicalTargetExclusion
		canonical  []string
		checkPaths []string
		active     map[string]records.ProjectionRecord
		want       string
	}{
		{name: "outside target", exclusion: CanonicalTargetExclusion{Path: "docs/other/file.md", Reason: "reason"}, want: "beneath one declared target root"},
		{name: "canonical input", exclusion: CanonicalTargetExclusion{Path: "docs/represented/canonical.yaml", Reason: "reason"}, canonical: []string{"docs/represented/canonical.yaml"}, want: "canonical input"},
		{name: "check input", exclusion: CanonicalTargetExclusion{Path: "docs/represented/check.yaml", Reason: "reason"}, checkPaths: []string{"docs/represented/check.yaml"}, want: "check input"},
		{name: "active ownership", exclusion: CanonicalTargetExclusion{Path: "docs/represented/owned.md", Reason: "reason"}, active: prior, want: "active artifact ownership"},
		{name: "case alias", exclusion: CanonicalTargetExclusion{Path: "Docs/represented/owned.md", Reason: "reason"}, active: prior, want: "beneath one declared target root"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			active := tc.active
			if active == nil {
				active = map[string]records.ProjectionRecord{}
			}
			err := validateCanonicalTargetExclusionScope([]CanonicalTargetExclusion{tc.exclusion}, requestIDs, requests, active, tc.canonical, tc.checkPaths)
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("unsafe exclusion accepted or wrong error: %v", err)
			}
		})
	}
	for _, bad := range []CanonicalTargetExclusion{
		{Path: "docs/represented/*.md", Reason: "reason"},
		{Path: "docs/represented/ok.md", Reason: "  "},
		{Path: "docs/represented/ok.md", Reason: strings.Repeat("x", 1025)},
	} {
		if err := validateCanonicalTargetExclusionConfig([]CanonicalTargetExclusion{bad}); err == nil {
			t.Fatalf("invalid owner exclusion accepted: %+v", bad)
		}
	}
	if err := validateCanonicalTargetExclusionConfig([]CanonicalTargetExclusion{{Path: "docs/represented/a.md", Reason: "one"}, {Path: "docs/represented/A.md", Reason: "two"}}); err == nil {
		t.Fatal("case-aliased exclusions were accepted")
	}
}

func TestControllerExclusionOutputGuard(t *testing.T) {
	for _, output := range []string{"docs/represented/out.md", "docs/represented/out.md/child.txt"} {
		if err := ValidateCanonicalControllerExclusionOutputs(map[string][]byte{output: []byte("candidate")}, []string{"docs/represented/out.md"}); err == nil {
			t.Fatalf("candidate output crossed excluded path boundary: %s", output)
		}
	}
	if err := ValidateCanonicalControllerExclusionOutputs(map[string][]byte{"docs/represented/other.md": []byte("candidate")}, []string{"docs/represented/out.md"}); err != nil {
		t.Fatalf("disjoint candidate output refused: %v", err)
	}
}

func TestDeletedTargetExclusionRemainsVisibleAsMissing(t *testing.T) {
	classified := classifyCanonicalTargetExclusions([]CanonicalTargetExclusion{{Path: "docs/represented/deleted.md", Reason: "out of scope"}}, map[string]source.WorkingFileMetadata{})
	if len(classified) != 1 || classified[0].State != "missing" || classified[0].Metadata != nil || classified[0].Reason != "out of scope" {
		t.Fatalf("missing exclusion metadata is not explicit: %+v", classified)
	}
}
