package markdown

import (
	"strings"
	"testing"

	"github.com/Glacius-Labs/Markitect/internal/core"
)

func fixture() (core.SemanticModel, Config) {
	m := core.SemanticModel{Resources: []core.ModelResource{
		{Identity: core.ModelIdentity{APIVersion: core.APIVersion, Kind: "Rule", Name: "privacy", Key: "policy/Rule/privacy"}, Data: map[string]any{"text": "Keep data safe."}, Source: core.ModelSource{Path: "docs/policy/nested/privacy.yaml"}, Area: "policy"},
		{Identity: core.ModelIdentity{APIVersion: core.APIVersion, Kind: "Skill", Name: "review", Key: "policy/Skill/review"}, Data: map[string]any{"description": "Review changes.", "text": "See [the rule](../nested/privacy.yaml)."}, Source: core.ModelSource{Path: "docs/policy/skills/review.skill.yml"}, Area: "policy"},
	}}
	m.Relationships = []core.ModelRelationship{{From: "policy/Skill/review", To: "policy/Rule/privacy", Type: "uses"}, {From: "policy/Skill/review", To: "policy/Rule/privacy", Type: "unrelated"}}
	c := Config{Enabled: true, ProjectKey: "Project/sample", Areas: []Area{{Name: "policy", Path: "docs/policy"}}}
	return m, c
}

func TestGenerateMarkdownViewsAndNavigationFromSemanticModel(t *testing.T) {
	m, c := fixture()
	outputs, owners, err := Generate(m, c, nil)
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range []string{"docs/markitect/policy/nested/privacy.rule.md", "docs/markitect/policy/skills/review.skill.md", "docs/markitect/policy/README.md", "docs/markitect/policy/nested/README.md", "docs/markitect/policy/skills/README.md", "docs/markitect/README.md"} {
		if outputs[p] == nil {
			t.Errorf("missing %s; got %v", p, sortedResourcePaths(outputs))
		}
	}
	body := string(outputs["docs/markitect/policy/skills/review.skill.md"])
	expected := "<!-- Generated by Markitect; source: docs/policy/skills/review.skill.yml -->\n# Skill: review\n\n**Description:** Review changes.\n\nSee [the rule](../nested/privacy.rule.md).\n\n## Dependencies\n\n- [Rule: privacy](../nested/privacy.rule.md)\n"
	if body != expected {
		t.Errorf("view bytes differ from the expected projection:\n--- got ---\n%s\n--- want ---\n%s", body, expected)
	}
	for _, want := range []string{"**Description:** Review changes.", "See [the rule](../nested/privacy.rule.md)."} {
		if !strings.Contains(body, want) {
			t.Errorf("view missing %q:\n%s", want, body)
		}
	}
	if !strings.Contains(body, "[Rule: privacy]") {
		t.Errorf("relationship projection missing:\n%s", body)
	}
	if strings.Contains(body, "unrelated") {
		t.Errorf("non-dependency relationship leaked into built-in view:\n%s", body)
	}
	if got := strings.Join(owners["docs/markitect/README.md"], ","); got != c.ProjectKey {
		t.Fatalf("root index owners %q", got)
	}
	second, _, err := Generate(m, c, nil)
	if err != nil {
		t.Fatal(err)
	}
	pathOwners, err := OutputPaths(m, c)
	if err != nil {
		t.Fatal(err)
	}
	if len(pathOwners) != len(outputs) {
		t.Fatalf("OutputPaths returned %d paths for %d generated outputs", len(pathOwners), len(outputs))
	}
	for p, b := range outputs {
		if string(b) != string(second[p]) {
			t.Fatalf("nondeterministic output %s", p)
		}
		if strings.Join(pathOwners[p], ",") != strings.Join(owners[p], ",") {
			t.Errorf("OutputPaths owners[%s]=%v, Generate owners=%v", p, pathOwners[p], owners[p])
		}
	}
}

func TestGenerateUsesFixedInputForCompanionAlias(t *testing.T) {
	m, c := fixture()
	m.Resources = m.Resources[:1]
	// The source-relative companion alias points at an ordinary file and must
	// retain that file when it exists without Markitect's ownership marker.
	m.Resources[0].Data["text"] = "See [companion](privacy.md)."
	files := map[string][]byte{"docs/policy/nested/privacy.md": []byte("Human-owned notes\n")}
	out, _, err := Generate(m, c, files)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out["docs/markitect/policy/nested/privacy.rule.md"]), "../../../policy/nested/privacy.md") {
		t.Fatalf("ordinary companion path was not retained: %s", out["docs/markitect/policy/nested/privacy.rule.md"])
	}
	files["docs/policy/nested/privacy.md"] = []byte("<!-- Generated by Markitect; source: old.yaml -->\n")
	out, _, err = Generate(m, c, files)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out["docs/markitect/policy/nested/privacy.rule.md"]), "(privacy.rule.md)") {
		t.Fatalf("generated companion alias was not redirected: %s", out["docs/markitect/policy/nested/privacy.rule.md"])
	}
}

func TestOutputPathsReservesProjectionWithoutEvaluatingProse(t *testing.T) {
	m, c := fixture()
	m.Resources[1].Data["text"] = "See [local file](C:/outside.md)."
	paths, err := OutputPaths(m, c)
	if err != nil {
		t.Fatal(err)
	}
	if paths["docs/markitect/policy/skills/review.skill.md"][0] != "policy/Skill/review" || paths["docs/markitect/README.md"][0] != c.ProjectKey {
		t.Fatalf("resource and index owners missing from path-only plan: %#v", paths)
	}
	if _, _, err := Generate(m, c, nil); err == nil {
		t.Fatal("Generate should still validate prose destinations")
	}
}

func TestViewPathsRejectCollisionAndMalformedArea(t *testing.T) {
	m, c := fixture()
	m.Resources = append(m.Resources, m.Resources[0])
	m.Resources[1].Source.Path = "docs/policy/nested/privacy.yml"
	m.Resources[1].Identity.Key = "policy/Rule/privacy2"
	if _, err := ViewPaths(m, c); err == nil || !strings.Contains(err.Error(), "Markdown view path collision") {
		t.Fatalf("expected deterministic view collision, got %v", err)
	}
	m, c = fixture()
	for i := range m.Resources {
		m.Resources[i].Area = ".."
	}
	c.Areas = []Area{{Name: "..", Path: "docs/policy"}}
	if _, err := ViewPaths(m, c); err == nil || !strings.Contains(err.Error(), "safe path segment") {
		t.Fatalf("expected malformed Area error, got %v", err)
	}
}

func TestGenerateCustomDomainContractUsesNormalizedModelAndPolicy(t *testing.T) {
	d := core.ModelDomain{Name: "Constitution", APIVersion: "constitution.example.org/v1alpha1", Kinds: map[string]core.KindDefinition{"Clause": {Required: []string{"category"}, Properties: map[string]core.PropertyDefinition{"category": {Type: "string"}}}}, Constraints: []core.ConstraintDefinition{{Name: "requires-core", Select: core.ResourceSelector{Kind: "Clause"}, Assert: core.ConstraintAssertion{Op: "allowed", Field: "category", Values: []any{"Core"}}}}}
	m := core.SemanticModel{Domains: []core.ModelDomain{d}, DomainInputs: []core.ModelDomainInput{{APIVersion: d.APIVersion, Name: d.Name, Path: "domains/constitution.yaml"}}, PolicyResults: []core.PolicyResult{
		{APIVersion: d.APIVersion, Constraint: "requires-core", Status: core.PolicyFailed, Message: "forbidden Module"},
		{APIVersion: d.APIVersion, Constraint: "waiver-example", Status: core.PolicyWaived, Message: "original violation", ExceptionName: "temporary", Rationale: "bounded reason", Owner: "platform", Decision: "ADR-42", ExpiresOn: "2027-01-31", PolicyDate: "2026-10-01"},
	}}
	out, _, err := Generate(m, Config{Enabled: true, ProjectKey: "Project/sample"}, nil)
	if err != nil {
		t.Fatal(err)
	}
	contract := string(out["docs/markitect/_domains/constitution.example.org.v1alpha1.domain.md"])
	for _, want := range []string{"# Domain contract: Constitution", "domains/constitution.yaml", "apiVersion: constitution.example.org/v1alpha1", "requires-core", "**FAILED**", "forbidden Module", "**WAIVED**", "exception: temporary", "rationale: bounded reason", "owner: platform", "decision: ADR-42", "2027-01-31", "2026-10-01"} {
		if !strings.Contains(contract, want) {
			t.Errorf("contract missing %q:\n%s", want, contract)
		}
	}
	if out["docs/markitect/README.md"] == nil || out["docs/markitect/_domains/README.md"] == nil {
		t.Fatal("domain indexes missing")
	}
}

func TestSelectedPackageDomainGetsContractAndIndexEntry(t *testing.T) {
	d := core.ModelDomain{Name: "engineering-constitution-v1", APIVersion: "engineering.markitect.org/v1alpha1", Kinds: map[string]core.KindDefinition{"Workflow": {Properties: map[string]core.PropertyDefinition{"intent": {Type: "string"}}}}}
	input := core.ModelDomainInput{APIVersion: d.APIVersion, Name: d.Name, Path: "domains/software.yaml", Package: "engineering-constitution", PackageVersion: "1.0.0"}
	m := core.SemanticModel{Domains: []core.ModelDomain{d}, DomainInputs: []core.ModelDomainInput{input}}
	out, owners, err := Generate(m, Config{Enabled: true, ProjectKey: "Project/consumer"}, nil)
	if err != nil {
		t.Fatal(err)
	}
	contractPath := "docs/markitect/_domains/engineering.markitect.org.v1alpha1.domain.md"
	contract := string(out[contractPath])
	if !strings.Contains(contract, "<!-- Generated by Markitect; source: domains/software.yaml -->") || !strings.Contains(contract, "- **Definition source:** `domains/software.yaml`") {
		t.Fatalf("selected package Domain lost the source path from its normalized DomainInput:\n%s", contract)
	}
	index := string(out["docs/markitect/_domains/README.md"])
	if !strings.Contains(index, "engineering-constitution-v1") || !strings.Contains(index, "source `domains/software.yaml`") {
		t.Fatalf("selected package Domain is absent from its index:\n%s", index)
	}
	if got := strings.Join(owners[contractPath], ","); got != "domain:engineering.markitect.org/v1alpha1/engineering-constitution-v1" {
		t.Fatalf("package Domain contract owners = %q", got)
	}
}

func TestDomainPolicySubjectLinksToItsResourceView(t *testing.T) {
	d := core.ModelDomain{Name: "Constitution", APIVersion: "constitution.example.org/v1alpha1", Kinds: map[string]core.KindDefinition{"Clause": {Properties: map[string]core.PropertyDefinition{"name": {Type: "string"}}}}}
	r := core.ModelResource{Identity: core.ModelIdentity{APIVersion: d.APIVersion, Kind: "Clause", Name: "review", Namespace: "policy", Key: "policy/Clause/review"}, Data: map[string]any{"name": "review"}, Source: core.ModelSource{Path: "resources/review.yaml"}, Area: "policy"}
	m := core.SemanticModel{Resources: []core.ModelResource{r}, Domains: []core.ModelDomain{d}, DomainInputs: []core.ModelDomainInput{{APIVersion: d.APIVersion, Name: d.Name, Path: "domains/constitution.yaml"}}, PolicyResults: []core.PolicyResult{{APIVersion: d.APIVersion, Constraint: "requires-review", Subject: r.Identity.Key, Status: core.PolicyFailed, Message: "review required"}}}
	out, _, err := Generate(m, Config{Enabled: true, ProjectKey: "Project/sample", Areas: []Area{{Name: "policy", Path: "resources"}}}, nil)
	if err != nil {
		t.Fatal(err)
	}
	contract := string(out["docs/markitect/_domains/constitution.example.org.v1alpha1.domain.md"])
	if !strings.Contains(contract, "[policy/Clause: review](../policy/review.clause.constitution.example.org.v1alpha1.md)") {
		t.Fatalf("domain PolicyResult subject lost its resource-view link:\n%s", contract)
	}
}

func TestApplicableRelationCountUsesDeclaredSourceKinds(t *testing.T) {
	d := core.ModelDomain{APIVersion: "relationships.example.org/v1", Relations: map[string]core.RelationDefinition{
		"dependsOn": {Field: "dependsOn", SourceKinds: []string{"Module"}, TargetKinds: []string{"Core"}},
	}, Constraints: []core.ConstraintDefinition{{Name: "module-has-dependency", Select: core.ResourceSelector{}, Assert: core.ConstraintAssertion{Op: "count", Scope: "resource", Relation: "dependsOn", Min: intPtr(1)}}}}
	m := core.SemanticModel{Domains: []core.ModelDomain{d}}
	module := core.ModelResource{Identity: core.ModelIdentity{APIVersion: d.APIVersion, Kind: "Module", Name: "orders", Key: "Module/orders"}}
	coreResource := core.ModelResource{Identity: core.ModelIdentity{APIVersion: d.APIVersion, Kind: "Core", Name: "platform", Key: "Core/platform"}}
	if got := constraints(module, m); len(got) != 1 || !strings.Contains(got[0].Text, "Each selected resource's count of `dependsOn` relationship targets must be at least 1") {
		t.Fatalf("Module relation constraint = %#v", got)
	}
	if got := constraints(coreResource, m); len(got) != 0 {
		t.Fatalf("Module-only constraint incorrectly selected Core: %#v", got)
	}
}

func TestCustomResourceViewProjectsStructuredFactsRelationshipsConstraintsAndWaiver(t *testing.T) {
	api := "constitution.example.org/v1alpha1"
	r := core.ModelResource{Identity: core.ModelIdentity{APIVersion: api, Kind: "Clause", Name: "review", Namespace: "policy", Key: "policy/Clause/review"}, Labels: map[string]string{"category": "security"}, Data: map[string]any{"description": "Protect private data.", "category": "security", "validators": []any{}}, Source: core.ModelSource{Path: "docs/policy/clauses/review.yaml"}, Area: "policy"}
	target := core.ModelResource{Identity: core.ModelIdentity{APIVersion: api, Kind: "Core", Name: "platform", Key: "policy/Core/platform"}, Data: map[string]any{}, Source: core.ModelSource{Path: "docs/policy/core/platform.yaml"}, Area: "policy"}
	d := core.ModelDomain{Name: "Constitution", APIVersion: api, Relations: map[string]core.RelationDefinition{"protects": {Field: "protects", SourceKinds: []string{"Clause"}, TargetKinds: []string{"Core"}}}, Constraints: []core.ConstraintDefinition{{Name: "category-required", Description: "Classify each clause.", Select: core.ResourceSelector{Kind: "Clause", Labels: map[string]string{"category": "security"}}, Assert: core.ConstraintAssertion{Op: "equal", Field: "category", Value: "security"}}}}
	m := core.SemanticModel{Resources: []core.ModelResource{r, target}, Relationships: []core.ModelRelationship{{From: r.Identity.Key, To: target.Identity.Key, Type: "protects"}}, Domains: []core.ModelDomain{d}, PolicyResults: []core.PolicyResult{{APIVersion: api, Constraint: "category-required", Subject: r.Identity.Key, Status: core.PolicyWaived, Message: "reviewed exception", ExceptionName: "temporary", Rationale: "migration", Owner: "policy team", Decision: "ADR-17"}}}
	c := Config{Enabled: true, ProjectKey: "Project/sample", Areas: []Area{{Name: "policy", Path: "docs/policy"}}}
	out, _, err := Generate(m, c, nil)
	if err != nil {
		t.Fatal(err)
	}
	body := string(out["docs/markitect/policy/clauses/review.clause.constitution.example.org.v1alpha1.md"])
	for _, want := range []string{"Protect private data.", "**category:** `security`", "**validators:** `[]`", "`protects` → protects Core: platform", "category-required", "must equal `security`", "Classify each clause.", "**WAIVED**", "reviewed exception", "temporary", "migration", "policy team", "ADR-17"} {
		if !strings.Contains(body, want) {
			t.Errorf("generic domain view missing %q:\n%s", want, body)
		}
	}
}

func TestPackageDependencyUsesOnlyExplicitHostPinAndRetainsUnpinnedInstruction(t *testing.T) {
	consumer := core.ModelResource{Identity: core.ModelIdentity{APIVersion: core.APIVersion, Kind: "Skill", Name: "review", Key: "Skill/review"}, Data: map[string]any{"text": "Review."}, Source: core.ModelSource{Path: "docs/policy/review.yaml"}, Area: "policy"}
	dependency := core.ModelResource{Identity: core.ModelIdentity{APIVersion: core.APIVersion, Kind: "Rule", Namespace: "security", Name: "privacy", Package: "security-kit", Key: "security-kit::security/Rule/privacy"}, Data: map[string]any{}, Source: core.ModelSource{Path: ""}}
	m := core.SemanticModel{Resources: []core.ModelResource{consumer, dependency}, Relationships: []core.ModelRelationship{{From: consumer.Identity.Key, To: dependency.Identity.Key, Type: "uses"}}}
	c := Config{Enabled: true, ProjectKey: "Project/sample", Areas: []Area{{Name: "policy", Path: "docs/policy"}}, Packages: map[string]string{"security-kit": "2.4.1"}}
	out, _, err := Generate(m, c, nil)
	if err != nil {
		t.Fatal(err)
	}
	body := string(out["docs/markitect/policy/review.skill.md"])
	expected := "<!-- Generated by Markitect; source: docs/policy/review.yaml -->\n# Skill: review\n\nReview.\n\n## Dependencies\n\n- Package dependency: security-kit::security/Rule/privacy (version 2.4.1). Select this exported dependency with `markitect context --repo . --package security-kit --namespace security --kind Rule --name privacy`.\n"
	if body != expected {
		t.Fatalf("package dependency output differs from the legacy byte contract:\n--- got ---\n%s\n--- want ---\n%s", body, expected)
	}
	for _, want := range []string{"Package dependency: security-kit::security/Rule/privacy (version 2.4.1)", "markitect context --repo . --package security-kit --namespace security --kind Rule --name privacy"} {
		if !strings.Contains(body, want) {
			t.Errorf("package output missing %q:\n%s", want, body)
		}
	}
	c.Packages = nil
	out, _, err = Generate(m, c, nil)
	if err != nil {
		t.Fatal(err)
	}
	body = string(out["docs/markitect/policy/review.skill.md"])
	if strings.Contains(body, "(version ") || !strings.Contains(body, "markitect context --repo . --package security-kit") {
		t.Fatalf("missing pin should omit only the version: %s", body)
	}
}

func intPtr(v int) *int { return &v }

func TestDisabledModuleProducesNoOutputs(t *testing.T) {
	out, owners, err := Generate(core.SemanticModel{}, Config{}, nil)
	if err != nil || len(out) != 0 || len(owners) != 0 {
		t.Fatalf("disabled outputs=%v owners=%v err=%v", out, owners, err)
	}
}
